import { describe, expect, it } from "vitest";
import { mkdir, mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { containerArtifacts, GENERATED_DOCKERFILE_MARKER } from "../src/deploy/container.ts";
import { fastagentVersion } from "../src/version.ts";
import { agentWorkspace, run } from "./cli-run.ts";

describe("cli: deploy", () => {
  it("selects the production value file and Docker env_file without reading dev values", async () => {
    const dir = await agentWorkspace("fa-deploy-env-", {
      "fastagent.config.ts": `export default { model: "openai/gpt-4o-mini" };\n`,
      ".secrets/.env": "FASTAGENT_MODEL=not-a-model\nFEISHU_INGRESS=websocket\nDEV_ONLY=secret\n",
      ".secrets/production/.env": "FASTAGENT_MODEL=openai/gpt-4o-mini\nPRODUCTION_ONLY=value\n",
    });
    const result = await run(["deploy", "docker", dir]);
    expect(result.code).toBe(0);
    expect(result.stderr).toContain("source: .secrets/production/.env");
    expect(result.stdout).toContain("PRODUCTION_ONLY");
    expect(result.stdout).not.toContain("DEV_ONLY");
    expect(await readFile(join(dir, "fastagent.compose.yml"), "utf8")).toContain(".secrets/production/.env");
  });

  it("an unattended first deploy requires production app values rather than reusing the dev app", async () => {
    const dir = await agentWorkspace("fa-deploy-new-app-", {
      "fastagent.config.ts": `export default { model: "openai/gpt-4o-mini" };\n`,
      ".secrets/.env": "FEISHU_APP_ID=cli_dev\nFEISHU_APP_SECRET=dev_secret\nFEISHU_VERIFICATION_TOKEN=dev_token\n",
      "channels/feishu.mjs": `const channel = () => ({ "POST /feishu": () => new Response("ok") });
channel.secrets = ["FEISHU_APP_ID", "FEISHU_APP_SECRET", "FEISHU_VERIFICATION_TOKEN"];
export default channel;\n`,
    });
    const result = await run(["deploy", "fly", dir, "--run", "--no-input"]);
    expect(result.code).toBe(1);
    expect(result.stderr).toContain(
      ".secrets/production/.env has no FEISHU_APP_ID, FEISHU_APP_SECRET, FEISHU_VERIFICATION_TOKEN",
    );
    expect(result.stderr).toContain("separate production app needs a terminal");
    expect(await readFile(join(dir, ".secrets", ".env"), "utf8")).toContain("FEISHU_APP_ID=cli_dev");
    await expect(stat(join(dir, "Dockerfile"))).rejects.toThrow();

    await mkdir(join(dir, ".secrets", "production"));
    await writeFile(join(dir, ".secrets", "production", ".env"), await readFile(join(dir, ".secrets", ".env"), "utf8"));
    const copied = await run(["deploy", "fly", dir, "--run", "--no-input"]);
    expect(copied.code).toBe(1);
    expect(copied.stderr).toContain("dev and production use the same app");
    await expect(stat(join(dir, "Dockerfile"))).rejects.toThrow();
  });

  it("deploy WIRES the ownership rule — the real command keeps a file it did not generate", async () => {
    // The rule itself (exists x ours x force) is a state machine, tested at its own level in
    // test/deploy-artifacts.test.ts; eight spawns proving it here made this the slowest and only flaky
    // test in the suite. What a subprocess is for is the WIRING: that the command actually consults it.
    const dir = await agentWorkspace("fa-deploy-ignore-", {
      "fastagent.config.ts": `export default { model: "openai-codex/gpt-5.5" };\n`,
      "package.json": `{"type":"module"}`,
    });
    expect((await run(["deploy", "fly", dir])).code).toBe(0);
    expect(await readFile(join(dir, ".dockerignore"), "utf8")).toMatch(/^# Generated by/);
    // Artifacts land in the agent directory.
    expect(await readFile(join(dir, "Dockerfile"), "utf8")).toMatch(/agent directory is baked at \/app\/definition/);
    expect(await readFile(join(dir, "fly.toml"), "utf8")).toMatch(/FASTAGENT_SECRETS_DIR/);

    const hostIgnore = "# the author's own rules\n.git\ndist\n"; // no marker → the author's
    await writeFile(join(dir, ".dockerignore"), hostIgnore);
    const forced = await run(["deploy", "fly", dir, "--force"]);
    expect(forced.code).toBe(0);
    // The safety boundary docs/deploy.md promises: --force NEVER clobbers the author's file.
    expect(await readFile(join(dir, ".dockerignore"), "utf8")).toBe(hostIgnore);
    expect(forced.stderr).toMatch(/kept \.dockerignore — not generated by fastagent/);
    expect(forced.stderr).toMatch(/BAKE SECRETS INTO THE IMAGE/); // the critical kept-file warn fired (not force-gated)
    expect(forced.stderr).toMatch(/excludes \.git/); // …and the history note
  });

  it("deploy agentcore --run with a login to redo and no terminal stops before touching AWS", async () => {
    // Every AgentCore deploy wipes the runtime's login; with nobody to redo it, the deploy would replace a serving
    // runtime with one that cannot answer. Decided up front, so no AWS command runs at all.
    const dir = await agentWorkspace("fa-deploy-ac-login-", {
      "fastagent.config.ts": `export default { model: "openai-codex/gpt-5.5" };\n`,
    });
    const bin = await mkdtemp(join(tmpdir(), "fa-aws-"));
    const called = join(bin, "called");
    await writeFile(join(bin, "aws"), `#!/bin/sh\necho "$@" >> ${called}\nexit 1\n`, { mode: 0o755 });
    const result = await run(["deploy", "agentcore", dir, "--run"], undefined, {
      ...process.env,
      PATH: `${bin}:${process.env.PATH}`,
    });
    expect(result.code).toBe(1);
    expect(result.stderr).toMatch(/wipes the runtime's openai-codex login.*run this deploy in a terminal/);
    await expect(stat(called)).rejects.toThrow(); // no aws invocation
  });

  it("deploy: generate mode succeeds with the WYSIWYG note; the agentDir config key is retired", async () => {
    const dir = await agentWorkspace("fa-deploy-gen-", {
      "fastagent.config.ts": `export default { model: "openai/gpt-4o-mini" };\n`,
    });
    const result = await run(["deploy", "fly", dir]);
    expect(result.code).toBe(0);
    expect(result.stderr).toMatch(/baked as the definition/); // the WYSIWYG bake note is stated
    expect(result.stderr).not.toMatch(/not yet supported/); // no placement gate anywhere

    // The retired config key fails visibly — placement is structural now, never configured.
    const legacy = await agentWorkspace("fa-deploy-legacy-", {
      "fastagent.config.ts": `export default { agentDir: "./agent" };\n`,
    });
    const rejected = await run(["deploy", "fly", legacy]);
    expect(rejected.code).toBe(1);
    expect(rejected.stderr).toMatch(/unknown key "agentDir"/);
  });

  it("never clobbers an existing Dockerfile: flags a stale generated one, warns on a hand-written one (G6)", async () => {
    // deploy KEEPS any existing Dockerfile without --force (no silent data loss). A generated one (marker)
    // that drifted from current config is flagged stale; a hand-written one is kept (preflight warns when the
    // environment then won't reach the image). An up-to-date generated one is kept quietly. Marker/predicate come
    // from container.ts (single source).
    const setup = async (dockerfileContent: string) => {
      const dir = await agentWorkspace("fa-kept-", {
        "fastagent.config.ts": `export default { model: "openai/gpt-4o-mini" };\n`,
        Dockerfile: dockerfileContent,
      });
      await writeFile(join(dir, "AGENTS.md"), "You are terse.\n");
      const res = await run(["deploy", "railway", dir]);
      return { res, dockerfile: await readFile(join(dir, "Dockerfile"), "utf8") };
    };

    // A generated-but-edited Dockerfile (marker kept, a hand-added line) → flagged stale, NEVER overwritten.
    const edited = `${GENERATED_DOCKERFILE_MARKER}. was generated\nFROM node:22-slim\nRUN echo my-own-edit\n`;
    const gen = await setup(edited);
    expect(gen.res.stderr).toMatch(/no longer matches what deploy would generate/); // stale flagged
    expect(gen.res.stderr).toMatch(/--force to regenerate/);
    expect(gen.dockerfile).toBe(edited); // preserved — the user's edit survives (no data loss)

    // An up-to-date generated Dockerfile (built with the SAME inputs deploy uses) → kept quietly, no stale flag.
    const current = containerArtifacts({
      releaseId: "release-one",
      agent: "any",
      hasPackageJson: false,
      runtime: "node",
      hasLockfile: false,
      version: await fastagentVersion(),
      apt: [],
    }).find((a) => a.path === "Dockerfile")!.content;
    const fresh = await setup(current);
    expect(fresh.res.stderr).not.toMatch(/no longer matches/); // identical → nothing to flag

    // A HAND-WRITTEN Dockerfile (no marker) → kept verbatim.
    const hw = await setup("FROM python:3.12\n");
    expect(hw.dockerfile).toBe("FROM python:3.12\n"); // preserved, never clobbered
  });
});
