/**
 * The ownership rule that decides what `deploy` may overwrite: a file fastagent generated carries a
 * marker and is refreshed under `--force`; a file it did not is never touched, whatever the flag says.
 *
 * It lives here rather than in the CLI e2e suite because it is a small state machine over
 * (exists, ours, force, alwaysWrite) — command LOGIC, which vitest.config.ts reserves this project's subprocess
 * tests against. Proving it by spawning `deploy` eight times made it the slowest test in the suite and
 * the only reliably flaky one (eight cold starts against a 30s ceiling, under file-parallel load). The
 * CLI keeps ONE spawn, for the wiring.
 */
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it, vi } from "vitest";
import { HOSTS, HOST_ONLY_FLAGS, warnHostOnlyFlags, writeArtifacts } from "../src/cli/commands/deploy.ts";
import { DEPLOY_HOSTS, type DeployHost } from "../src/deploy/hosts.ts";

/** Each artifact kind: the opening bytes that make it OURS, and WHO answers for it. A host answers
 *  only its own kind; "container" is the pair `writeArtifacts` answers itself, for every host. */
const MARKERS = {
  "fastagent/Dockerfile": { marker: "# Generated by `fastagent deploy`", owner: "container" },
  ".dockerignore": { marker: "# Generated by `fastagent deploy`", owner: "container" },
  "fastagent/fastagent.compose.yml": { marker: "# Generated by `fastagent deploy docker`", owner: "docker" },
  "fastagent/fly.toml": { marker: "# Generated by `fastagent deploy fly`", owner: "fly" },
  "fastagent/railway.json": { marker: `{ "x-generated-by": "fastagent deploy railway" }`, owner: "railway" },
  "fastagent/agentcore.template.yaml": { marker: "# Generated by `fastagent deploy agentcore`", owner: "agentcore" },
} as const satisfies Record<string, { marker: string; owner: DeployHost | "container" }>;
type Kind = keyof typeof MARKERS;

/** What the dispatcher binds for the host being deployed — ONE host's predicate, never a union over
 *  all of them: the union is what a misrouted or missing predicate would hide, since it answers for
 *  every kind whoever is deploying. The container's two get a predicate that claims nothing, which is
 *  the claim: `writeArtifacts` owns them whatever the host says. */
const isOursFor = (path: Kind): ((p: string, c: string) => boolean) => {
  const { owner } = MARKERS[path];
  return owner === "container" ? () => false : HOSTS[owner].isOurs;
};

/** Generated content for `path`: the marker must OPEN the file, which is the rule being tested. */
const generatedFor = (path: Kind): string =>
  path.endsWith("railway.json") ? `${MARKERS[path].marker}\n` : `${MARKERS[path].marker}\nfresh\n`;

/** Run one write against a fresh dir seeded with `existing`, capturing what the command said. */
async function attempt(
  path: Kind,
  existing: string | undefined,
  force: boolean,
): Promise<{ content: string; said: string }> {
  const dir = await mkdtemp(join(tmpdir(), "fa-own-"));
  if (existing !== undefined) {
    await mkdir(dirname(join(dir, path)), { recursive: true });
    await writeFile(join(dir, path), existing);
  }
  const said: string[] = [];
  const spy = vi.spyOn(console, "error").mockImplementation((m: unknown) => said.push(String(m)));
  try {
    await writeArtifacts(dir, [{ path, content: generatedFor(path) }], { force, isOurs: isOursFor(path) });
  } finally {
    spy.mockRestore();
  }
  return { content: await readFile(join(dir, path), "utf8"), said: said.join("\n") };
}

describe("deploy: ownership decides what --force may replace", () => {
  it("a file fastagent did NOT generate survives --force — every artifact kind", async () => {
    // The table must know every kind: one missing reads as the author's forever, which silently turns
    // --force into a no-op for it (`fly.toml` and `railway.json` were exactly that bug).
    for (const path of Object.keys(MARKERS) as Kind[]) {
      const mine = path.endsWith("railway.json") ? `{ "app": "mine" }\n` : "hand written, no marker\n";
      const r = await attempt(path, mine, true);
      expect(r.content, path).toBe(mine);
      expect(r.said, path).toMatch(/not generated by fastagent/);
    }
  });

  it("`alwaysWrite` is the ONE exemption: build output that must track the template it belongs to", async () => {
    // AgentCore's Lambda forwarder is generated code, not operator-owned configuration — a stale copy
    // beside a fresh template is a broken deployment. It is the one path that skips the rule, so it is
    // named at the call site rather than inferred from the kind, and the exemption is proven here.
    const path = "fastagent/lambda/index.js";
    const dir = await mkdtemp(join(tmpdir(), "fa-own-"));
    await mkdir(dirname(join(dir, path)), { recursive: true });
    await writeFile(join(dir, path), "// mine\n");
    const said: string[] = [];
    const spy = vi.spyOn(console, "error").mockImplementation((m: unknown) => said.push(String(m)));
    try {
      await writeArtifacts(dir, [{ path, content: "// fresh\n" }], {
        force: false,
        alwaysWrite: [path],
        isOurs: () => false,
      });
    } finally {
      spy.mockRestore();
    }
    expect(await readFile(join(dir, path), "utf8")).toBe("// fresh\n"); // overwritten without --force
    expect(said.join("\n")).toMatch(/wrote fastagent\/lambda\/index\.js/);
  });

  it("a marker that does not OPEN the file is not ours (a header above it is the author's edit)", async () => {
    const path = "fastagent/fly.toml";
    const disguised = `# my own header\n${generatedFor(path)}`;
    expect((await attempt(path, disguised, true)).content).toBe(disguised);
  });

  it("every host claims its OWN artifact kind and no other host's", () => {
    // The predicate the dispatcher binds is one host's, so a host that claims a neighbour's kind (or
    // whose kind no host claims) is how `--force` becomes a silent no-op. Same types everywhere, so
    // nothing but this asserts the pairing.
    for (const path of Object.keys(MARKERS) as Kind[]) {
      const { owner } = MARKERS[path];
      for (const host of DEPLOY_HOSTS) {
        expect(HOSTS[host].isOurs(path, generatedFor(path)), `${host} vs ${path}`).toBe(host === owner);
      }
    }
  });

  it("ours is kept without --force and regenerated with it", async () => {
    const path = "fastagent/Dockerfile";
    const stale = `${MARKERS[path].marker}\nedited by me\n`;

    const kept = await attempt(path, stale, false);
    expect(kept.content).toBe(stale); // the edit survives
    expect(kept.said).toMatch(/no longer matches what deploy would generate/); // …and names --force

    const forced = await attempt(path, stale, true);
    expect(forced.content).toBe(generatedFor(path));
    expect(forced.said).toMatch(/wrote fastagent\/Dockerfile/);
  });

  it("ours and unchanged says so; an absent artifact is simply written", async () => {
    const path = ".dockerignore";
    expect((await attempt(path, generatedFor(path), false)).said).toMatch(/kept \.dockerignore \(unchanged\)/);

    const fresh = await attempt(path, undefined, false);
    expect(fresh.content).toBe(generatedFor(path));
    expect(fresh.said).toMatch(/wrote \.dockerignore/);
  });

  it("a kept file's message names ITS consequence, not a generic one", async () => {
    // Pointing every kind at "the preflight warnings" would send the reader looking for output that is
    // only ever printed for the ignore file.
    expect((await attempt("fastagent/Dockerfile", "FROM python:3.12\n", true)).said).toMatch(
      /assumes it listens on \$PORT/,
    );
    expect((await attempt(".dockerignore", "mine\n", true)).said).toMatch(/see the preflight warnings/);
    const toml = (await attempt("fastagent/fly.toml", 'app = "mine"\n', true)).said;
    expect(toml).toMatch(/not generated by fastagent/);
    expect(toml).not.toMatch(/\$PORT|preflight warnings/);
  });
});

describe("deploy: a flag only one host honours is reported the same way by every other host", () => {
  const said = (host: Parameters<typeof warnHostOnlyFlags>[0], opts: Parameters<typeof warnHostOnlyFlags>[1]) => {
    const lines: string[] = [];
    const spy = vi.spyOn(console, "error").mockImplementation((m: unknown) => void lines.push(String(m)));
    try {
      warnHostOnlyFlags(host, opts);
    } finally {
      spy.mockRestore();
    }
    return lines.join("\n");
  };

  it("names the owning host in ONE spelling, whichever host is refusing the flag", () => {
    // The drift this replaces: `Railway-only` from docker/agentcore, `railway-only` from fly.
    for (const host of ["docker", "agentcore", "fly"] as const) {
      expect(said(host, { intoLinked: true })).toContain("--into-linked: railway-only");
    }
    for (const host of ["docker", "railway", "agentcore"] as const) {
      expect(said(host, { stop: true })).toContain("--stop/--no-scale-to-zero: fly-only");
    }
  });

  it("says what THAT host does instead — the sentence is the reason it is not a generic no-op notice", () => {
    expect(said("railway", { scaleToZero: false })).toMatch(/App Sleeping is a dashboard toggle/);
    expect(said("agentcore", { scaleToZero: false })).toMatch(/LifecycleConfiguration/);
    expect(said("fly", { intoLinked: true })).toMatch(/idempotent/);
  });

  it("stays silent for the owner, and for a flag nobody passed", () => {
    expect(said("fly", { stop: true, scaleToZero: false })).toBe("");
    expect(said("railway", { intoLinked: true })).toBe("");
    expect(said("docker", {})).toBe("");
  });
});

describe("deploy: every host-only flag has a line for every other host", () => {
  // The type says so — `instead: Record<Exclude<DeployHost, Owner>, string>` — but that guarantee is
  // load-bearing on how the table is TYPED, and the natural move when adding a third rule is to relax
  // it to `HostOnlyFlag<DeployHost>[]`, where `Exclude<DeployHost, DeployHost>` is `never` and an
  // empty `instead` type-checks. Asserting the DATA holds whatever the annotation becomes.
  it("covers every non-owner host, with a non-empty sentence", () => {
    for (const rule of HOST_ONLY_FLAGS) {
      const expected = DEPLOY_HOSTS.filter((host) => host !== rule.owner);
      const instead = rule.instead as Record<string, string>;
      expect(Object.keys(instead).sort()).toEqual([...expected].sort());
      for (const host of expected) expect(instead[host]).toBeTruthy();
    }
  });

  it("names an owner that is a real deploy host", () => {
    for (const rule of HOST_ONLY_FLAGS) expect(DEPLOY_HOSTS).toContain(rule.owner);
  });
});
