/**
 * The ownership rule that decides what `deploy` may overwrite: a file fastagent generated carries a
 * marker and is refreshed under `--force`; a file it did not is never touched, whatever the flag says.
 *
 * It lives here rather than in the CLI e2e suite because it is a small state machine over
 * (exists, ours, force, alwaysWrite) — command LOGIC, which vitest.config.ts reserves this project's subprocess
 * tests against. Proving it by spawning `deploy` eight times made it the slowest test in the suite and
 * the only reliably flaky one (eight cold starts against a 30s ceiling, under file-parallel load). The
 * CLI keeps ONE spawn, for the wiring.
 */
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it, vi } from "vitest";
import { writeArtifacts } from "../src/cli/commands/deploy.ts";

/** The opening bytes that make each artifact kind OURS — one per kind the ownership table knows. */
const MARKERS = {
  "fastagent/Dockerfile": "# Generated by `fastagent deploy`",
  ".dockerignore": "# Generated by `fastagent deploy`",
  "fastagent/fastagent.compose.yml": "# Generated by `fastagent deploy docker`",
  "fastagent/fly.toml": "# Generated by `fastagent deploy fly`",
  "fastagent/railway.json": `{ "x-generated-by": "fastagent deploy railway" }`,
  "fastagent/agentcore.template.yaml": "# Generated by `fastagent deploy agentcore`",
} as const;
type Kind = keyof typeof MARKERS;

/** Generated content for `path`: the marker must OPEN the file, which is the rule being tested. */
const generatedFor = (path: Kind): string =>
  path.endsWith("railway.json") ? `${MARKERS[path]}\n` : `${MARKERS[path]}\nfresh\n`;

/** Run one write against a fresh dir seeded with `existing`, capturing what the command said. */
async function attempt(
  path: Kind,
  existing: string | undefined,
  force: boolean,
): Promise<{ content: string; said: string }> {
  const dir = await mkdtemp(join(tmpdir(), "fa-own-"));
  if (existing !== undefined) {
    await mkdir(dirname(join(dir, path)), { recursive: true });
    await writeFile(join(dir, path), existing);
  }
  const said: string[] = [];
  const spy = vi.spyOn(console, "error").mockImplementation((m: unknown) => said.push(String(m)));
  try {
    await writeArtifacts(dir, [{ path, content: generatedFor(path) }], { force });
  } finally {
    spy.mockRestore();
  }
  return { content: await readFile(join(dir, path), "utf8"), said: said.join("\n") };
}

describe("deploy: ownership decides what --force may replace", () => {
  it("a file fastagent did NOT generate survives --force — every artifact kind", async () => {
    // The table must know every kind: one missing reads as the author's forever, which silently turns
    // --force into a no-op for it (`fly.toml` and `railway.json` were exactly that bug).
    for (const path of Object.keys(MARKERS) as Kind[]) {
      const mine = path.endsWith("railway.json") ? `{ "app": "mine" }\n` : "hand written, no marker\n";
      const r = await attempt(path, mine, true);
      expect(r.content, path).toBe(mine);
      expect(r.said, path).toMatch(/not generated by fastagent/);
    }
  });

  it("`alwaysWrite` is the ONE exemption: build output that must track the template it belongs to", async () => {
    // AgentCore's Lambda forwarder is generated code, not operator-owned configuration — a stale copy
    // beside a fresh template is a broken deployment. It is the one path that skips the rule, so it is
    // named at the call site rather than inferred from the kind, and the exemption is proven here.
    const path = "fastagent/lambda/index.js";
    const dir = await mkdtemp(join(tmpdir(), "fa-own-"));
    await mkdir(dirname(join(dir, path)), { recursive: true });
    await writeFile(join(dir, path), "// mine\n");
    const said: string[] = [];
    const spy = vi.spyOn(console, "error").mockImplementation((m: unknown) => said.push(String(m)));
    try {
      await writeArtifacts(dir, [{ path, content: "// fresh\n" }], { force: false, alwaysWrite: [path] });
    } finally {
      spy.mockRestore();
    }
    expect(await readFile(join(dir, path), "utf8")).toBe("// fresh\n"); // overwritten without --force
    expect(said.join("\n")).toMatch(/wrote fastagent\/lambda\/index\.js/);
  });

  it("a marker that does not OPEN the file is not ours (a header above it is the author's edit)", async () => {
    const path = "fastagent/fly.toml";
    const disguised = `# my own header\n${generatedFor(path)}`;
    expect((await attempt(path, disguised, true)).content).toBe(disguised);
  });

  it("ours is kept without --force and regenerated with it", async () => {
    const path = "fastagent/Dockerfile";
    const stale = `${MARKERS[path]}\nedited by me\n`;

    const kept = await attempt(path, stale, false);
    expect(kept.content).toBe(stale); // the edit survives
    expect(kept.said).toMatch(/no longer matches what deploy would generate/); // …and names --force

    const forced = await attempt(path, stale, true);
    expect(forced.content).toBe(generatedFor(path));
    expect(forced.said).toMatch(/wrote fastagent\/Dockerfile/);
  });

  it("ours and unchanged says so; an absent artifact is simply written", async () => {
    const path = ".dockerignore";
    expect((await attempt(path, generatedFor(path), false)).said).toMatch(/kept \.dockerignore \(unchanged\)/);

    const fresh = await attempt(path, undefined, false);
    expect(fresh.content).toBe(generatedFor(path));
    expect(fresh.said).toMatch(/wrote \.dockerignore/);
  });

  it("a kept file's message names ITS consequence, not a generic one", async () => {
    // Pointing every kind at "the preflight warnings" would send the reader looking for output that is
    // only ever printed for the ignore file.
    expect((await attempt("fastagent/Dockerfile", "FROM python:3.12\n", true)).said).toMatch(
      /assumes it listens on \$PORT/,
    );
    expect((await attempt(".dockerignore", "mine\n", true)).said).toMatch(/see the preflight warnings/);
    const toml = (await attempt("fastagent/fly.toml", 'app = "mine"\n', true)).said;
    expect(toml).toMatch(/not generated by fastagent/);
    expect(toml).not.toMatch(/\$PORT|preflight warnings/);
  });
});
