// Generated by `fastagent deploy agentcore` — the deployment's only ingress.
// (Inside fastagent this file IS the source; the sentence below applies to the copy it is emitted as,
// the agent directory's `lambda/index.js`.)
// REGENERATED ON EVERY DEPLOY; edits here are overwritten and never deployed. `--run` builds the
// Lambda package from fastagent's own copy of this source, so this file is the readable MIRROR of
// what runs (and what the manual runbook zips) — not an input you can change.
// Webhooks (Function URL) and EventBridge Scheduler fires are forwarded as envelopes to the
// AgentCore Runtime over SigV4 InvokeAgentRuntime, all on ONE fixed ingress session (fastagent
// channel state is single-writer; one session = at most one microVM). This
// Lambda also OWNS the alarms: the container POSTs its schedules and pending wake-ups to
// /__fastagent/wake-alarm (shared secret). Each schedule becomes a RECURRING EventBridge cron schedule
// that delivers each instant's fire on EventBridge's own clock; each wake-up becomes a self-deleting
// one-shot that pokes the container, whose wake pump fires the due entry.
// CommonJS on purpose: the deployment package's entry lands as index.js, where ESM import is invalid.
"use strict";
const crypto = require("node:crypto");
const { BedrockAgentCoreClient, InvokeAgentRuntimeCommand } = require("@aws-sdk/client-bedrock-agentcore");
const client = new BedrockAgentCoreClient({});
let ownUrl; // self-resolved once per cold start; rides on every envelope for the wake-alarm callback

// Every shared-secret gate on this public URL goes through here. Constant-time, and an unset
// expected secret NEVER matches — otherwise a topology that did not configure one would accept a
// request that sent none. Non-string input is coerced to "" first: Buffer.from(8) allocates eight
// bytes rather than throwing, which would compare a number against a secret by length alone.
const secretEq = (given, expected) => {
  const a = Buffer.from(typeof given === "string" ? given : ""),
    b = Buffer.from(expected || "");
  return b.length > 0 && a.length === b.length && crypto.timingSafeEqual(a, b);
};

async function invoke(envelope) {
  if (process.env.WAKE_SECRET && !ownUrl) {
    const { LambdaClient, GetFunctionUrlConfigCommand } = require("@aws-sdk/client-lambda");
    ownUrl = (
      await new LambdaClient({}).send(
        new GetFunctionUrlConfigCommand({ FunctionName: process.env.AWS_LAMBDA_FUNCTION_NAME }),
      )
    ).FunctionUrl;
  }
  if (ownUrl) envelope.wake = { url: ownUrl };
  // Authenticates this envelope as coming from the forwarder (see the template's FastagentIngressSecret).
  envelope.auth = process.env.INGRESS_SECRET;
  const res = await client.send(
    new InvokeAgentRuntimeCommand({
      agentRuntimeArn: process.env.RUNTIME_ARN,
      runtimeSessionId: process.env.INGRESS_SESSION_ID,
      contentType: "application/json",
      accept: "application/json",
      payload: new TextEncoder().encode(JSON.stringify(envelope)),
    }),
  );
  const body = Buffer.from(await res.response.transformToByteArray());
  return { status: res.statusCode ?? 200, body };
}

/** The EventBridge name for one alarm id: prefix + a stable hash of the WHOLE id. */
const mintedName = (prefix, id) => prefix + crypto.createHash("sha256").update(id).digest("hex").slice(0, 16);

// Mirror the container's pending wake-ups into one-shot schedules: at(fireAt), poke me, delete after firing. Upsert
// (create → conflict → update): an id names one instant, so the update is the same alarm mirrored again, never a
// spent one moved. The container pre-filters DUE alarms (it is awake handling those), so every failure here is REAL —
// counted and propagated: a swallowed error would leave a pending wake with no alarm, exactly the reliability hole
// this mechanism closes. Cancelled wakes are NOT deleted here: their poke fires, finds nothing due, and the schedule
// self-deletes (lazy cleanup by design).
async function syncAlarms(sch, alarms, ctx) {
  const { CreateScheduleCommand, UpdateScheduleCommand } = require("@aws-sdk/client-scheduler");
  let failed = 0;
  // Alarm name = a stable hash of the WHOLE alarm id. A prefix of the id would collide (two alarms
  // sharing 8 hex chars), and a collision is INDISTINGUISHABLE from the legitimate re-mirror below:
  // the second alarm would "update" the first and silently steal its fire time.
  const names = new Map();
  for (const a of alarms) {
    const name = mintedName(process.env.WAKE_PREFIX, a.id);
    if (names.has(name)) {
      failed += 1;
      console.log(`alarm name collision ${name}: ${names.get(name)} vs ${a.id}`);
      continue;
    }
    names.set(name, a.id);
    const p = {
      Name: name,
      ScheduleExpression: `at(${a.at.slice(0, 19)})`,
      ScheduleExpressionTimezone: "UTC",
      FlexibleTimeWindow: { Mode: "OFF" },
      ActionAfterCompletion: "DELETE",
      // It only wakes the container, whose pump fires what is due.
      Target: { Arn: ctx.invokedFunctionArn, RoleArn: process.env.WAKE_ROLE_ARN, Input: '{"wakePoke":true}' },
    };
    try {
      await sch.send(new CreateScheduleCommand(p));
    } catch (e) {
      try {
        if (e.name !== "ConflictException") throw e;
        await sch.send(new UpdateScheduleCommand(p));
      } catch (u) {
        failed += 1;
        console.log(`alarm ${p.Name}: ${u}`);
      }
    }
  }
  return failed;
}

// Make the recurring schedules exactly the container's set: create what is missing, update what differs, delete what
// it no longer has. Declarative, so a delete that failed is retried by the next sync, and the update is skipped when
// nothing changed (every sync carries the whole set, and a sync follows every wake-up too). Only names this Lambda
// mints are deleted: a prefix alone also matches a sibling agent named `<name>-sc-…`.
async function syncSchedules(sch, schedules, ctx) {
  const {
    CreateScheduleCommand,
    UpdateScheduleCommand,
    GetScheduleCommand,
    DeleteScheduleCommand,
    ListSchedulesCommand,
  } = require("@aws-sdk/client-scheduler");
  const prefix = process.env.SCHEDULE_PREFIX;
  const held = new Set();
  let NextToken;
  do {
    const page = await sch.send(new ListSchedulesCommand({ NamePrefix: prefix, NextToken }));
    for (const s of page.Schedules || []) {
      if (s.Name.startsWith(prefix) && /^[0-9a-f]{16}$/.test(s.Name.slice(prefix.length))) held.add(s.Name);
    }
    NextToken = page.NextToken;
  } while (NextToken);
  let failed = 0;
  const wanted = new Set();
  for (const s of schedules) {
    const p = {
      Name: mintedName(prefix, s.name),
      ScheduleExpression: s.expression,
      ScheduleExpressionTimezone: s.tz,
      FlexibleTimeWindow: { Mode: "OFF" },
      State: "ENABLED",
      // <aws.scheduler.scheduled-time> is the clock's NAME for this occurrence: EventBridge repeats it byte-identical
      // on every redelivery, which is what makes the container's claim work.
      Target: {
        Arn: ctx.invokedFunctionArn,
        RoleArn: process.env.WAKE_ROLE_ARN,
        Input: JSON.stringify({ scheduleFire: { name: s.name, occurrence: "<aws.scheduler.scheduled-time>" } }),
      },
    };
    wanted.add(p.Name);
    try {
      if (!held.has(p.Name)) {
        await sch.send(new CreateScheduleCommand(p));
        continue;
      }
      const now = await sch.send(new GetScheduleCommand({ Name: p.Name }));
      // Every field this Lambda sets. RoleArn too: the role's name is CloudFormation's, so a stack recreated over a
      // schedule left behind gives it a new one, and a schedule still naming the old role never fires again.
      const same =
        now.ScheduleExpression === p.ScheduleExpression &&
        now.ScheduleExpressionTimezone === p.ScheduleExpressionTimezone &&
        now.State === p.State &&
        now.Target?.Input === p.Target.Input &&
        now.Target?.Arn === p.Target.Arn &&
        now.Target?.RoleArn === p.Target.RoleArn;
      if (!same) await sch.send(new UpdateScheduleCommand(p));
    } catch (e) {
      failed += 1;
      console.log(`schedule ${s.name} (${p.Name}): ${e}`);
    }
  }
  for (const name of held) {
    if (wanted.has(name)) continue;
    try {
      await sch.send(new DeleteScheduleCommand({ Name: name }));
    } catch (e) {
      if (e.name === "ResourceNotFoundException") continue;
      failed += 1;
      console.log(`schedule ${name} (delete): ${e}`);
    }
  }
  return failed;
}

/**
 * Invoke the container, and leave ONE line under `label` whichever way it ends — including the way that never came
 * back at all.
 *
 * Lambda already logs an unhandled throw, so the failure is not invisible; what it is not is ATTRIBUTABLE. An
 * operator (or a probe) filtering this log group for `schedule-fire <name>` sees nothing and concludes the clock
 * never fired, when what actually happened is that the clock fired and the call died. Those need different fixes
 * and looked identical from outside — that mistake cost a real debugging session.
 */
async function invokeLogged(label, envelope) {
  try {
    return await invoke(envelope);
  } catch (e) {
    console.log(`${label}: invoke failed: ${e?.message || e}`);
    throw e; // the miss still lands as a Lambda error, which is what makes EventBridge retry it
  }
}

exports.handler = async (event, ctx) => {
  // EventBridge wake-up poke: the invocation itself wakes the container; its pump does the rest.
  if (event?.wakePoke) {
    const r = await invokeLogged("wake-poke", { kind: "wake-poke" });
    console.log(`wake-poke: ${r.status}`);
    return { status: r.status };
  }
  // EventBridge Scheduler fire — throw on failure so the miss lands in CloudWatch, never silently.
  if (event?.scheduleFire) {
    const { name, occurrence } = event.scheduleFire;
    const label = `schedule-fire ${name} (${occurrence})`;
    const r = await invokeLogged(label, { kind: "schedule-fire", name, occurrence });
    const out = r.body.toString();
    console.log(`${label}: ${r.status} ${out}`);
    if (r.status >= 400) throw new Error(`schedule-fire ${name} failed: ${r.status} ${out}`);
    return { status: r.status };
  }
  const http = event?.requestContext?.http;
  if (!http) throw new Error("unrecognized event shape");
  // The container's wake-alarm callback (reserved path, shared secret) — handled HERE, never forwarded.
  if (event.rawPath === "/__fastagent/wake-alarm") {
    const req = JSON.parse(event.isBase64Encoded ? Buffer.from(event.body, "base64").toString() : event.body || "{}");
    if (!secretEq(req.secret, process.env.WAKE_SECRET)) return { statusCode: 403, body: "forbidden\n" };
    const { SchedulerClient } = require("@aws-sdk/client-scheduler");
    const sch = new SchedulerClient({});
    // A sync request names the WHOLE schedule set; one without it is not a sync, and deleting every schedule on it
    // would be the wrong answer.
    if (!Array.isArray(req.schedules)) return { statusCode: 400, body: "schedules: expected the whole set\n" };
    const failed = (await syncAlarms(sch, req.alarms || [], ctx)) + (await syncSchedules(sch, req.schedules, ctx));
    // Partial failure IS failure: the container retries the whole (idempotent) set until every
    // schedule and pending wake really has its EventBridge schedule.
    if (failed > 0) return { statusCode: 500, body: `${failed} alarm(s) failed\n` };
    return { statusCode: 200, body: "ok\n" };
  }
  // Preserve the trusted probe's structured verdict instead of folding its diagnostics into a 502.
  // Schedule-only topologies also need this path, before the ordinary webhook gate.
  if (event.rawPath === "/__fastagent/probe") {
    const req = JSON.parse(event.isBase64Encoded ? Buffer.from(event.body, "base64").toString() : event.body || "{}");
    if (!secretEq(req.auth, process.env.INGRESS_SECRET)) return { statusCode: 403, body: "forbidden\n" };
    const r = await invoke({ kind: "probe" });
    if (r.status !== 200) {
      console.log(`probe transport error ${r.status}: ${r.body}`);
      return { statusCode: 502, body: "upstream error\n" };
    }
    return { statusCode: 200, headers: { "content-type": "application/json" }, body: r.body.toString() };
  }
  // Enforce the advertised ORIGINAL-body ceiling before base64 adds another 4/3 inside the runtime
  // envelope. This also leaves deterministic room for headers/query/JSON under Lambda's 6 MB cap.
  const webhookBytes =
    event.body === undefined
      ? 0
      : event.isBase64Encoded
        ? Buffer.byteLength(event.body, "base64")
        : Buffer.byteLength(event.body);
  // The ceiling rides in as an env var (the template's MAX_WEBHOOK_BODY_BYTES), so a stack whose
  // template predates it would compare against NaN — every comparison false, the limit silently gone.
  const maxWebhookBytes = Number(process.env.MAX_WEBHOOK_BODY_BYTES);
  if (!(maxWebhookBytes > 0))
    throw new Error("MAX_WEBHOOK_BODY_BYTES is missing or invalid — redeploy to regenerate the stack template");
  if (webhookBytes > maxWebhookBytes) return { statusCode: 413, body: "payload too large\n" };
  // A schedule-only deployment has a Function URL solely for the authenticated refresh callback.
  // Reject arbitrary public traffic BEFORE it can wake AgentCore (cost/DoS) or reach an inner route.
  if (process.env.WEBHOOKS_ENABLED !== "1") return { statusCode: 404, body: "not found\n" };
  // Function URL webhook — forward the original request verbatim (signature material included).
  const r = await invoke({
    kind: "webhook",
    method: http.method,
    path: event.rawPath || "/",
    query: event.rawQueryString || undefined,
    headers: event.headers || {},
    bodyB64:
      event.body === undefined
        ? undefined
        : event.isBase64Encoded
          ? event.body
          : Buffer.from(event.body).toString("base64"),
  });
  if (r.status !== 200) {
    console.log(`transport error ${r.status}: ${r.body}`);
    return { statusCode: 502, body: "upstream error\n" };
  }
  const reply = JSON.parse(r.body.toString()); // { status, headers, bodyB64 } from the adapter
  for (const k of Object.keys(reply.headers)) {
    if (/^(content-length|transfer-encoding|connection)$/i.test(k)) delete reply.headers[k];
  }
  return { statusCode: reply.status, headers: reply.headers, body: reply.bodyB64, isBase64Encoded: true };
};
