/** `fastagent deploy fly` — the Fly.io deploy PLAN, computed from the resolved definition. */
import type { DeclaredChannel } from "../../channels/discover.ts";
import { webhookRunbook } from "../channel-ingress.ts";
import { type Artifact, type ContainerInput, containerArtifacts } from "../container.ts";
import { CRON_CAN_BE_EXTERNAL, type Residency, WAKEUPS_WHEN_ASLEEP, residencyFor } from "../residency.ts";
import { type DeploymentSecret, isEnvKey } from "../secrets.ts";

export interface FlyPlanInput extends ContainerInput {
  // Container facts (hasPackageJson, runtime, hasLockfile, bunVersion, version, apt) come from ContainerInput.
  /** Fly app name — globally unique, lowercase; the CLI sanitizes it from the dir basename. */
  appName: string;
  /** The port the app listens on (config.http.port ?? 8787); fly.toml routes to it. */
  port: number;
  /** What satisfies model auth locally ({@link probeAuthSource}). */
  modelAuth: string | undefined;
  /**
   * Every declared channel and its ingress — the source of the webhook steps, and whether a machine
   * must stay up for an outbound connection.
   */
  channels: readonly DeclaredChannel[];
  /**
   * The runbook's variable list (`deploymentSecrets`): what must have a value, then everything else the value file
   * carries.
   */
  secrets?: readonly DeploymentSecret[];
  /** `routines/` declares a cron — one of the things that forces a machine up (deploy/residency.ts). */
  hasCron: boolean;
}

export interface FlyPlan {
  /** fly.toml / Dockerfile / .dockerignore — written by the CLI (skipped if present unless --force). */
  artifacts: Artifact[];
  /** The ordered, values-resolved deploy runbook — printed to stdout for the coding agent to execute. */
  runbook: string[];
}

function flyToml(appName: string, port: number, residency: Residency | undefined): string {
  // WHY is residency.ts's to decide; the SETTING and its wording are Fly's. Anything else is an edit to the
  // generated file, which is the artifact's job.
  const min = residency
    ? `  min_machines_running = 1         # ${residency.why}`
    : `  min_machines_running = 0         # scale to zero — ${WAKEUPS_WHEN_ASLEEP}`;
  // The one reason with a way out gets it stated NEXT TO the line it is about, which is where an operator reading
  // `min_machines_running = 1` and wondering what it costs them is looking.
  const alternative =
    residency?.reason === CRON_CAN_BE_EXTERNAL
      ? `  # …or keep the time somewhere else and set this to 0: a scheduler you own (Fly Cron Manager,\n` +
        `  # supercronic, GitHub Actions) calls \`POST /run\`, which runs one declared unit of work by name.\n` +
        `  # It is an API, not a clock: read its contract first — docs/api-reference.md#post-run.\n` +
        `  # At 0, ${WAKEUPS_WHEN_ASLEEP}.\n`
      : "";
  // Suspend, not stop: a resume is fast enough that a webhook does not time out. Edit the line to change it.
  const stopLine = `  auto_stop_machines = "suspend"   # suspend on idle (fast resume on the next webhook)`;
  return `${GENERATED_FLY_TOML_MARKER}. Edit freely — it is not regenerated unless you pass --force.
app = "${appName}"
primary_region = "iad"  # set your region (list: \`fly platform regions\`)

[build]

[env]
  FASTAGENT_STATE_DIR = "/data/.state"      # mutable machine state — sessions, channel state, schedule
  FASTAGENT_SECRETS_DIR = "/data/.secrets"  # seeded (and rotated) credentials — must persist across restarts
  PORT = "${port}"

[http_service]
  internal_port = ${port}
  force_https = true
${stopLine}
  auto_start_machines = true
${min}
${alternative}
[mounts]
  source = "data"
  destination = "/data"            # workspace, state and credentials survive stop/suspend/redeploy
  initial_size = "1gb"             # the volume is created by the FIRST deploy — it is pinned to one host, and only
                                   # deploy tells the scheduler which machine (size + image) must fit there too

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"                 # suspend is not recommended above 2 GB
`;
}

/** First line of a generated `fly.toml`, and the predicate that reads it back. */
const GENERATED_FLY_TOML_MARKER = "# Generated by `fastagent deploy fly`";

export function isGeneratedFlyToml(content: string): boolean {
  return content.startsWith(GENERATED_FLY_TOML_MARKER);
}

/** Compute the Fly deploy plan from the resolved definition. */
export function planFlyDeploy(input: FlyPlanInput): FlyPlan {
  const { appName, port, modelAuth, channels } = input;
  // Artifacts sit under the agent prefix, so they never touch the workspace's own deploy files.
  const flyTomlPath = `${input.agentPrefix}fly.toml`;
  const artifacts: Artifact[] = [
    {
      path: flyTomlPath,
      content: flyToml(appName, port, residencyFor({ channels, hasCron: input.hasCron })),
    },
    ...containerArtifacts(input),
  ];

  const secrets = input.secrets ?? [];

  const deployCmd = `fly deploy . --config ${flyTomlPath} --dockerfile ${input.agentPrefix}Dockerfile --app ${appName}`;
  const runbook: string[] = [
    `# Deploy "${appName}" to Fly.io. ${flyTomlPath} / Dockerfile(.dockerignore) are generated above.`,
    `# Prereqs: flyctl installed (https://fly.io/docs/flyctl/install) and \`fly auth login\`.`,
    ``,
    `# One-time setup (skip on a redeploy — a second run makes a SECOND app/volume, splitting state).`,
    `# Fly app names are GLOBALLY unique: if this fails as taken, set a unique "app" in fly.toml and`,
    `# re-run \`fastagent deploy fly\` — the runbook follows fly.toml's app name.`,
    `fly apps create ${appName}`,
    `# The volume (workspace, state, credentials — kept across stop/suspend/redeploy) is created by the deploy`,
    `# below, in primary_region and sized by [mounts].initial_size. Creating it yourself first pins it to a host`,
    `# picked without the machine, which can fail the deploy with "insufficient resources … existing volume".`,
    ``,
    `# An address to be reached ON: [http_service] declares a service, it does not allocate an IP.`,
    `# \`fly deploy\` allocates one on a FIRST deploy only, and merely WARNS when that fails — which`,
    `# leaves the machine serving and https://${appName}.fly.dev with no DNS record at all. Both are`,
    `# free; skip if \`fly ips list --app ${appName}\` already shows a v4/v6/shared_v4 address:`,
    `fly ips allocate-v4 --shared --app ${appName}`,
    `fly ips allocate-v6 --app ${appName}`,
  ];

  if (secrets.length > 0) {
    runbook.push(
      ``,
      `# Secrets (replace each <value>):`,
      ...secrets.map((s) => `#   ${s.name}: ${s.hint}`),
      `fly secrets set --app ${appName} ${secrets.map((s) => `${s.name}=<value>`).join(" ")}`,
    );
  }
  runbook.push(
    ``,
    `# The build context is the WORKSPACE ROOT (the whole directory is baked as the agent's cwd).`,
    `# The config/Dockerfile live under ${input.agentPrefix} so they never collide with the workspace's own.`,
    `# Before a new definition release, run \`fastagent deploy fly\` to refresh the release manifest.`,
    `# Run this from the workspace root:`,
    deployCmd,
  );
  runbook.push(
    ``,
    `# The volume keeps /data/base (including uncommitted work), .state and .secrets across restarts and deploys.`,
    `# Each generated release replaces only /data/base/${input.agentPrefix}; other workspace files are initialized once.`,
    input.shipsGit
      ? `# Git is available for optional collaboration. Verify uploaded history with \`git status\`; clone if the host stripped it.`
      : `# To use Git for collaboration, add deploy: { apt: ["git"] }. Storage durability does not require Git.`,
  );

  // Model-auth guidance: an env key becomes a secret above.
  if (!isEnvKey(modelAuth)) {
    runbook.push(
      ``,
      modelAuth === undefined
        ? `# Model auth: none found at the local auth path — a global \`fastagent login\` isn't read here; set FASTAGENT_AUTH_PATH (e.g. ~/.fastagent/.secrets/auth.json), or \`--run\` carries it automatically.`
        : `# Model auth: your local auth is "${modelAuth}" — the plan can't read its value to set as a secret.`,
      `#   Set your provider API key as a Fly secret (fly secrets set KEY=...), OR place auth.json at /data/.secrets/ on the volume.`,
    );
  }

  // The fastagent-only post-step: point each channel at the live URL.
  const steps = webhookRunbook(`https://${appName}.fly.dev`, channels);
  const post = steps.length > 0 ? [`# After deploy:`, ...steps] : [];
  if (post.length > 0) runbook.push(``, ...post);

  // Single-machine tier: state lives on ONE volume tied to ONE machine.
  runbook.push(
    ``,
    `# Keep this a SINGLE machine: the /data volume (and all state on it) is tied to one machine.`,
    `# Multiple machines would each get their own volume and split sessions/turns — don't scale past 1.`,
  );

  return { artifacts, runbook };
}

/** The `app` name from an existing fly.toml's `app = "…"` line, or undefined if absent. */
export function parseFlyAppName(toml: string): string | undefined {
  return toml.match(/^\s*app\s*=\s*["']([^"']+)["']/m)?.[1];
}

/** The `min_machines_running` from a fly.toml, or undefined. */
export function parseFlyMinMachines(toml: string): number | undefined {
  const m = toml.match(/^\s*min_machines_running\s*=\s*(\d+)/m)?.[1];
  return m === undefined ? undefined : Number(m);
}

/** Sanitize a directory basename into a Fly app name: lowercase, [a-z0-9-], must start with a letter. */
export function toFlyAppName(basename: string): string {
  const slug = basename
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return /^[a-z]/.test(slug) ? slug : `app-${slug || "agent"}`;
}
