/** `fastagent deploy fly` — the Fly.io deploy PLAN, computed from the resolved definition. */
import type { DeclaredChannel } from "../../channels/discover.ts";
import { webhookRunbook } from "../channel-ingress.ts";
import { type Artifact, type ContainerInput, containerArtifacts } from "../container.ts";
import { deploymentSecrets, isEnvKey } from "../secrets.ts";

export interface FlyPlanInput extends ContainerInput {
  // Container facts (hasPackageJson, runtime, hasLockfile, bunVersion, version, apt) come from ContainerInput.
  /** Fly app name — globally unique, lowercase; the CLI sanitizes it from the dir basename. */
  appName: string;
  /** The port the app listens on (config.http.port ?? 8787); fly.toml routes to it. */
  port: number;
  /** What satisfies model auth locally ({@link probeAuthSource}). */
  modelAuth: string | undefined;
  /**
   * Every declared channel and its ingress — the source of the secret list, the webhook steps, and whether a machine
   * must stay up for an outbound connection.
   */
  channels: readonly DeclaredChannel[];
  /** Extra secret env-var names (fastagent.config deploy.secrets) — added to the runbook's secret list. */
  extraSecrets?: string[];
  /** `auto_stop_machines` — `"suspend"` (default, fast resume) or `"stop"` (cold start). */
  autostop: "suspend" | "stop";
  /** Allow scaling to zero when idle (default true → `min_machines_running=0`). */
  scaleToZero: boolean;
  /**
   * Time triggers present (schedules/ or selfSchedule) — forces one machine up: cron/wake has no external wake-up, so
   * a scaled-to-zero box would sleep through them.
   */
  hasTimeTriggers: boolean;
}

export interface FlyPlan {
  /** fly.toml / Dockerfile / .dockerignore — written by the CLI (skipped if present unless --force). */
  artifacts: Artifact[];
  /** The ordered, values-resolved deploy runbook — printed to stdout for the coding agent to execute. */
  runbook: string[];
}

function flyToml(
  appName: string,
  port: number,
  hasGithub: boolean,
  autostop: "suspend" | "stop",
  scaleToZero: boolean,
  hasTimeTriggers: boolean,
  hasLongConnectionChannel: boolean,
): string {
  // min_machines_running: 1 (keep one up) when a github channel is present, TIME triggers exist, OR the operator
  // opted out of scale-to-zero.
  const min = hasGithub
    ? `  min_machines_running = 1         # github turns have no replay — don't scale to zero (an in-flight review would be lost)`
    : hasTimeTriggers
      ? `  min_machines_running = 1         # schedules/wake-ups need a running machine (no external wake-up for a cron instant)`
      : hasLongConnectionChannel
        ? `  min_machines_running = 1         # long-connection channel needs a running machine (cannot wake from zero)`
        : !scaleToZero
          ? `  min_machines_running = 1         # kept running (--no-scale-to-zero)`
          : `  min_machines_running = 0         # scale to zero`;
  const stopLine =
    autostop === "stop"
      ? `  auto_stop_machines = "stop"      # stop on idle (cold start on the next webhook)`
      : `  auto_stop_machines = "suspend"   # suspend on idle (fast resume on the next webhook)`;
  return `${GENERATED_FLY_TOML_MARKER}. Edit freely — it is not regenerated unless you pass --force.
app = "${appName}"
primary_region = "iad"  # set your region (list: \`fly platform regions\`)

[build]

[env]
  FASTAGENT_STATE_DIR = "/data/.state"      # mutable machine state — sessions, channel state, schedule
  FASTAGENT_SECRETS_DIR = "/data/.secrets"  # seeded (and rotated) credentials — must persist across restarts
  PORT = "${port}"

[http_service]
  internal_port = ${port}
  force_https = true
${stopLine}
  auto_start_machines = true
${min}

[mounts]
  source = "data"
  destination = "/data"            # workspace, state and credentials survive stop/suspend/redeploy

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"                 # suspend is not recommended above 2 GB
`;
}

/** First line of a generated `fly.toml`, and the predicate that reads it back. */
const GENERATED_FLY_TOML_MARKER = "# Generated by `fastagent deploy fly`";

export function isGeneratedFlyToml(content: string): boolean {
  return content.startsWith(GENERATED_FLY_TOML_MARKER);
}

/** Compute the Fly deploy plan from the resolved definition. */
export function planFlyDeploy(input: FlyPlanInput): FlyPlan {
  const { appName, port, modelAuth, channels } = input;
  // Artifacts sit under the agent prefix, so a NESTED agent never touches the workspace's own deploy files.
  const flyTomlPath = `${input.agentPrefix}fly.toml`;
  const artifacts: Artifact[] = [
    {
      path: flyTomlPath,
      content: flyToml(
        appName,
        port,
        channels.some((channel) => channel.name === "github"),
        input.autostop,
        input.scaleToZero,
        input.hasTimeTriggers,
        channels.some((channel) => channel.ingress === "long-connection"),
      ),
    },
    ...containerArtifacts(input),
  ];

  // The exact secret list the deployed machine needs, computed from the definition (host-neutral).
  const secrets = deploymentSecrets(modelAuth, channels, input.extraSecrets);
  const requiredSecrets = secrets.filter((secret) => secret.required);
  const optionalSecrets = secrets.filter((secret) => !secret.required);

  const deployCmd = `fly deploy . --config ${flyTomlPath} --dockerfile ${input.agentPrefix}Dockerfile --app ${appName}`;
  const runbook: string[] = [
    `# Deploy "${appName}" to Fly.io. ${flyTomlPath} / Dockerfile(.dockerignore) are generated above.`,
    `# Prereqs: flyctl installed (https://fly.io/docs/flyctl/install) and \`fly auth login\`.`,
    ``,
    `# One-time setup (skip on a redeploy — a second run makes a SECOND app/volume, splitting state).`,
    `# Fly app names are GLOBALLY unique: if this fails as taken, set a unique "app" in fly.toml and`,
    `# re-run \`fastagent deploy fly\` — the runbook follows fly.toml's app name.`,
    `fly apps create ${appName}`,
    `# The volume persists the workspace, state and credentials across stop/suspend/redeploy.`,
    `# <region> MUST equal primary_region in fly.toml (a volume in another region can't mount) — fly.toml`,
    `# is the single source for the region; skip this if the volume exists (fly volumes list --app ${appName}):`,
    `fly volumes create data --app ${appName} --region <region> --size 1`,
    ``,
    `# An address to be reached ON: [http_service] declares a service, it does not allocate an IP.`,
    `# \`fly deploy\` allocates one on a FIRST deploy only, and merely WARNS when that fails — which`,
    `# leaves the machine serving and https://${appName}.fly.dev with no DNS record at all. Both are`,
    `# free; skip if \`fly ips list --app ${appName}\` already shows a v4/v6/shared_v4 address:`,
    `fly ips allocate-v4 --shared --app ${appName}`,
    `fly ips allocate-v6 --app ${appName}`,
  ];

  if (requiredSecrets.length > 0) {
    runbook.push(
      ``,
      `# Required secrets (replace each <value>):`,
      ...requiredSecrets.map((s) => `#   ${s.name}: ${s.hint}`),
      `fly secrets set --app ${appName} ${requiredSecrets.map((s) => `${s.name}=<value>`).join(" ")}`,
    );
  }
  if (optionalSecrets.length > 0) {
    runbook.push(
      ``,
      `# Optional secrets — set only when the matching feature is configured:`,
      ...optionalSecrets.map((s) => `#   ${s.name}: ${s.hint}`),
      `# fly secrets set --app ${appName} ${optionalSecrets.map((s) => `${s.name}=<value>`).join(" ")}`,
    );
  }
  runbook.push(
    ``,
    `# The build context is the WORKSPACE ROOT (the whole directory is baked as the agent's cwd).`,
    `# The config/Dockerfile live under ${input.agentPrefix} so they never collide with the workspace's own.`,
    `# Before a new definition release, run \`fastagent deploy fly\` to refresh the release manifest.`,
    `# Run this from the workspace root:`,
    deployCmd,
  );
  runbook.push(
    ``,
    `# The volume keeps /data/base (including uncommitted work), .state and .secrets across restarts and deploys.`,
    `# Each generated release replaces only /data/base/${input.agentPrefix}; other workspace files are initialized once.`,
    input.shipsGit
      ? `# Git is available for optional collaboration. Verify uploaded history with \`git status\`; clone if the host stripped it.`
      : `# To use Git for collaboration, add deploy: { apt: ["git"] }. Storage durability does not require Git.`,
  );

  // Model-auth guidance: an env key becomes a secret above.
  if (!isEnvKey(modelAuth)) {
    runbook.push(
      ``,
      modelAuth === undefined
        ? `# Model auth: none found at the local auth path — a global \`fastagent login\` isn't read here; pass --auth-path <file> (e.g. ~/.fastagent/.secrets/auth.json), or \`--run\` carries it automatically.`
        : `# Model auth: your local auth is "${modelAuth}" — the plan can't read its value to set as a secret.`,
      `#   Set your provider API key as a Fly secret (fly secrets set KEY=...), OR place auth.json at /data/.secrets/ on the volume.`,
    );
  }

  // The fastagent-only post-step: point each channel at the live URL.
  const steps = webhookRunbook(`https://${appName}.fly.dev`, channels);
  const post = steps.length > 0 ? [`# After deploy:`, ...steps] : [];
  if (post.length > 0) runbook.push(``, ...post);

  // Single-machine tier: state lives on ONE volume tied to ONE machine.
  runbook.push(
    ``,
    `# Keep this a SINGLE machine: the /data volume (and all state on it) is tied to one machine.`,
    `# Multiple machines would each get their own volume and split sessions/turns — don't scale past 1.`,
  );

  return { artifacts, runbook };
}

/** The `app` name from an existing fly.toml's `app = "…"` line, or undefined if absent. */
export function parseFlyAppName(toml: string): string | undefined {
  return toml.match(/^\s*app\s*=\s*["']([^"']+)["']/m)?.[1];
}

/** The `primary_region` from a fly.toml, or undefined. */
export function parseFlyRegion(toml: string): string | undefined {
  return toml.match(/^\s*primary_region\s*=\s*["']([^"']+)["']/m)?.[1];
}

/** The `min_machines_running` from a fly.toml, or undefined. */
export function parseFlyMinMachines(toml: string): number | undefined {
  const m = toml.match(/^\s*min_machines_running\s*=\s*(\d+)/m)?.[1];
  return m === undefined ? undefined : Number(m);
}

/** Sanitize a directory basename into a Fly app name: lowercase, [a-z0-9-], must start with a letter. */
export function toFlyAppName(basename: string): string {
  const slug = basename
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return /^[a-z]/.test(slug) ? slug : `app-${slug || "agent"}`;
}
