/**
 * `fastagent deploy docker` — the local-Docker plan. The application image stays ingress-neutral:
 * this target generates only the shared Dockerfile plus a small Compose service for the FastAgent
 * process, its loopback port, exact environment-variable names, and one persistent state volume.
 * `--tunnel` can add an ephemeral Cloudflare Quick Tunnel service; durable ingress remains operator-owned.
 */
import type { ChannelKind } from "../../scaffold/add-channel.ts";
import { type Artifact, type ContainerInput, containerArtifacts } from "../container.ts";
import { deploymentSecrets, isEnvKey } from "../secrets.ts";

export interface DockerPlanInput extends ContainerInput {
  /** Stable Compose project name, sanitized by {@link toDockerProjectName}. */
  projectName: string;
  /** Container + default host port. The host binding is loopback-only by default. */
  port: number;
  /** What satisfies model auth locally: an env-var name, an OAuth/stored label, or undefined. */
  modelAuth: string | undefined;
  /** Known channels contribute their environment-variable names and webhook registration. */
  channels: ChannelKind[];
  /** Generate an optional Cloudflare Quick Tunnel service in Compose. Generation only; `--run` starts it. */
  tunnel: boolean;
  /** Extra environment-variable names declared in config.deploy.secrets. */
  extraSecrets?: string[];
}

export interface DockerPlan {
  /** fastagent.compose.yml + the shared Dockerfile/ignore artifacts. */
  artifacts: Artifact[];
  /** Compose file path relative to the workspace root (namespaced for agentDir layouts). */
  composePath: string;
  /** Ordered local build/run/operate instructions. */
  runbook: string[];
}

const MOUNT = "/data";
export const DOCKER_COMPOSE_FILE = "fastagent.compose.yml";
export const GENERATED_COMPOSE_MARKER = "# Generated by `fastagent deploy docker`";
/** Pinned: generated deployment artifacts must not silently move when Cloudflare publishes `latest`. */
export const CLOUDFLARED_IMAGE = "cloudflare/cloudflared:2026.7.1";

/** Whether a Compose file still opts into generated-drift warnings (drop the marker after taking ownership). */
export function isGeneratedCompose(content: string): boolean {
  return content.startsWith(GENERATED_COMPOSE_MARKER);
}

/** Whether an authoritative Compose file already carries the generated tunnel service contract. */
export function composeHasTunnelService(content: string): boolean {
  return /^\s{2}tunnel:\s*(?:#.*)?$/m.test(content);
}

/** Compose project names are lowercase [a-z0-9_-] and must start with an alphanumeric character. */
export function toDockerProjectName(directoryName: string): string {
  const slug = directoryName
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "")
    .slice(0, 54)
    .replace(/[-_]+$/g, "");
  return `fastagent-${slug || "agent"}`;
}

/** Default first-party webhook paths. Workspace glue may remap them, so guidance labels them defaults. */
export function dockerWebhookPaths(channels: ChannelKind[]): string[] {
  const path: Record<ChannelKind, string> = {
    github: "/webhook",
    telegram: "/telegram",
    feishu: "/feishu",
    lark: "/lark",
  };
  return channels.map((kind) => path[kind]);
}

/** `${NAME:-}` without making JavaScript treat it as interpolation. */
function composeInterpolation(name: string): string {
  return `\${${name}:-}`;
}

/** Relative path from the namespaced Compose file's directory back to the workspace/build root. */
function buildContext(kitDir?: string): string {
  if (!kitDir) return ".";
  return kitDir
    .split("/")
    .map(() => "..")
    .join("/");
}

function composeYaml(input: DockerPlanInput): string {
  const secrets = deploymentSecrets(input.modelAuth, input.channels, input.extraSecrets);
  // Always leave the auth-seed seam in the committed topology. `--run` uses it for OAuth/stored auth;
  // it is empty otherwise. Values never land in this file — Compose interpolates them at invocation.
  const envNames = [...new Set([...secrets.map((secret) => secret.name), "FASTAGENT_AUTH_SEED"])];
  const secretEnv = envNames.map((name) => `      ${name}: "${composeInterpolation(name)}"`).join("\n");
  const context = buildContext(input.kitDir);
  const dockerfile = input.kitDir ? `${input.kitDir}/Dockerfile` : "Dockerfile";
  const tunnelService = input.tunnel
    ? `
  # Cloudflare Quick Tunnel: ephemeral URL, generated only with \`deploy docker --tunnel\`.
  # No restart policy on purpose: a new process gets a new URL and needs webhook re-registration.
  tunnel:
    image: ${CLOUDFLARED_IMAGE}
    command:
      - tunnel
      - --no-autoupdate
      - --url
      - http://agent:${input.port}
    depends_on:
      - agent
    environment:
      # Docker Desktop may inject HTTP(S)_PROXY into containers. The origin is Docker-internal and must
      # bypass it; preserve any operator NO_PROXY entries after the required service/loopback names.
      NO_PROXY: "agent,localhost,127.0.0.1,${composeInterpolation("NO_PROXY")}"
      no_proxy: "agent,localhost,127.0.0.1,${composeInterpolation("no_proxy")}"
    restart: "no"
`
    : "";

  return `${GENERATED_COMPOSE_MARKER}. Edit freely — it is kept unless you pass --force.
# Durable/public ingress remains yours; --tunnel optionally adds an ephemeral Quick Tunnel service.
name: ${input.projectName}

services:
  agent:
    build:
      context: ${context}
      dockerfile: ${dockerfile}
    ports:
      - "127.0.0.1:${input.port}:${input.port}"
    environment:
      PORT: "${input.port}"
      FASTAGENT_STATE_DIR: "${MOUNT}"
${secretEnv}
    volumes:
      - state:${MOUNT}
    restart: unless-stopped
${tunnelService}
volumes:
  state:
`;
}

/** Compute local-Docker artifacts + the runbook; no Docker process is touched here. */
export function planDockerDeploy(input: DockerPlanInput): DockerPlan {
  const composePath = input.kitDir ? `${input.kitDir}/${DOCKER_COMPOSE_FILE}` : DOCKER_COMPOSE_FILE;
  const artifacts: Artifact[] = [{ path: composePath, content: composeYaml(input) }, ...containerArtifacts(input)];
  const compose = `docker compose -f ${composePath}`;
  const secrets = deploymentSecrets(input.modelAuth, input.channels, input.extraSecrets);
  const required = secrets.filter((secret) => secret.required);
  const optional = secrets.filter((secret) => !secret.required);
  const paths = dockerWebhookPaths(input.channels);

  const runbook: string[] = [
    `# Run FastAgent in local Docker. ${composePath} / Dockerfile(.dockerignore) are generated above.`,
    `# Existing artifacts are authoritative and kept; edit Dockerfile or ${composePath} freely.`,
    `# Prereqs: Docker Engine/Desktop with the Compose plugin (\`docker compose version\`).`,
  ];

  if (required.length > 0) {
    runbook.push(
      `# Required environment values (put them in the workspace .env or export them):`,
      ...required.map((secret) => `#   ${secret.name}: ${secret.hint}`),
    );
  }
  if (optional.length > 0) {
    runbook.push(`# Optional environment values:`, ...optional.map((secret) => `#   ${secret.name}: ${secret.hint}`));
  }
  if (!isEnvKey(input.modelAuth)) {
    runbook.push(
      input.modelAuth === undefined
        ? `# Model auth: none found locally — run \`fastagent login\` or set a provider API key before --run.`
        : `# Model auth: local source is "${input.modelAuth}" — \`--run\` carries auth.json as FASTAGENT_AUTH_SEED.`,
      `# For a manual Compose run, provide a provider API key or set FASTAGENT_AUTH_SEED yourself.`,
    );
  }

  if (input.kitDir) {
    runbook.push(
      `# Repo-as-workspace: run from the REPO ROOT. Compose lives under ${input.kitDir}/ but builds`,
      `# the whole repository; only the kit's dependencies are installed by ${input.kitDir}/Dockerfile.`,
    );
  }

  runbook.push(
    ``,
    `# Build/create/reconcile the service. Re-running this is the complete local redeploy; state stays`,
    `# in the Compose volume mounted at ${MOUNT}.`,
    `${compose} up -d --build`,
    `curl --fail http://127.0.0.1:${input.port}/health`,
    ``,
    `# Operate it:`,
    `${compose} logs -f agent`,
    `${compose} ps`,
    `${compose} down        # stops containers; keeps the state volume`,
    `# ${compose} down -v   # DESTRUCTIVE: also deletes auth, sessions, and channel state`,
  );

  if (input.tunnel) {
    runbook.push(
      ``,
      `# Quick Tunnel: \`--run\` starts the Compose tunnel service and reads its ephemeral public URL.`,
      `# Detected Telegram/Feishu/Lark channels auto-register; GitHub prints the URL. Re-run after the`,
      `# tunnel container/Docker daemon restarts: a new Quick Tunnel URL must replace the old webhook URL.`,
      `${compose} logs -f tunnel`,
    );
  } else if (paths.length > 0) {
    runbook.push(
      ``,
      `# Public ingress is operator-owned: add your tunnel/proxy/DNS/TLS, then configure the`,
      `# detected default endpoint(s): ${paths.map((path) => `https://<your-domain>${path}`).join(", ")}.`,
      `# If your channels/*.ts glue remaps a route, use that path instead.`,
    );
  }

  runbook.push(
    `# Keep one agent replica: the local state volume is single-process; multiple replicas split/corrupt state.`,
  );

  return { artifacts, composePath, runbook };
}
