/** `fastagent deploy docker` — the local-Docker plan. */
import type { DeclaredChannel } from "../../channels/discover.ts";
import { webhookPaths } from "../channel-ingress.ts";
import { type Artifact, type ContainerInput, containerArtifacts } from "../container.ts";
import { deploymentLoginCommand } from "../box-shell.ts";
import type { DeploymentSecret } from "../secrets.ts";
import { SECRETS_DIRNAME } from "../../paths.ts";

export interface DockerPlanInput extends ContainerInput {
  /** Stable Compose project name, sanitized by {@link toDockerProjectName}. */
  projectName: string;
  /** Container + default host port. */
  port: number;
  /**
   * The provider the deployment logs in to itself (`fastagent login --deployment`): its credential is not a variable
   * the plan carries.
   */
  boxLogin?: string;
  /** Every declared channel and its ingress — the source of the ingress note. */
  channels: readonly DeclaredChannel[];
  /** Generate an optional Cloudflare Quick Tunnel service in Compose. */
  tunnel: boolean;
  /**
   * The runbook's variable list (`deploymentSecrets`): what must have a value, then everything else the value file
   * carries.
   */
  secrets?: readonly DeploymentSecret[];
  /** The value file as the pre-flight resolved it (it follows `FASTAGENT_SECRETS_DIR`), agent-dir-relative. */
  valueFile: string;
}

export interface DockerPlan {
  /** fastagent.compose.yml + the shared Dockerfile/ignore artifacts. */
  artifacts: Artifact[];
  /** Compose file path relative to the agent directory. */
  composePath: string;
  /** Ordered local build/run/operate instructions. */
  runbook: string[];
}

const MOUNT = "/data";
export const DOCKER_COMPOSE_FILE = "fastagent.compose.yml";
export const DOCKER_VALUE_FILE = `${SECRETS_DIRNAME}/production/.env`;
const GENERATED_COMPOSE_MARKER = "# Generated by `fastagent deploy docker`";
export const MIN_DOCKER_COMPOSE_VERSION = "2.3.3";
/** Pinned: generated deployment artifacts must not silently move when Cloudflare publishes `latest`. */
export const CLOUDFLARED_IMAGE = "cloudflare/cloudflared:2026.7.1";

/** Whether a Compose file still opts into generated-drift warnings (drop the marker after taking ownership). */
export function isGeneratedCompose(content: string): boolean {
  return content.startsWith(GENERATED_COMPOSE_MARKER);
}

/** Whether an authoritative Compose file already carries the generated tunnel service contract. */
export function composeHasTunnelService(content: string): boolean {
  return /^[ \t]+tunnel:\s*(?:#.*)?$/m.test(content);
}

/** Compose project names are lowercase [a-z0-9_-] and must start with an alphanumeric character. */
export function toDockerProjectName(directoryName: string): string {
  const slug = directoryName
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "")
    .slice(0, 54)
    .replace(/[-_]+$/g, "");
  return `fastagent-${slug || "agent"}`;
}

/** `${NAME:-}` without making JavaScript treat it as interpolation. */
function composeInterpolation(name: string): string {
  return `\${${name}:-}`;
}

function composeYaml(input: DockerPlanInput): string {
  // Compose sits beside the Dockerfile, in the agent directory, which is the build context.
  const tunnelService = input.tunnel
    ? `
  # Cloudflare Quick Tunnel: ephemeral URL, generated only with \`deploy docker --tunnel\`.
  # No restart policy on purpose: a new process gets a new URL and needs webhook re-registration.
  tunnel:
    image: ${CLOUDFLARED_IMAGE}
    command:
      - tunnel
      - --no-autoupdate
      - --url
      - http://agent:${input.port}
    depends_on:
      - agent
    environment:
      # Docker Desktop may inject HTTP(S)_PROXY into containers. The origin is Docker-internal and must
      # bypass it; preserve any operator NO_PROXY entries after the required service/loopback names.
      NO_PROXY: "agent,localhost,127.0.0.1,${composeInterpolation("NO_PROXY")}"
      no_proxy: "agent,localhost,127.0.0.1,${composeInterpolation("no_proxy")}"
    # Quieter than the agent, but bounded for the same reason: nothing else on this host bounds it.
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: "no"
`
    : "";

  return `${GENERATED_COMPOSE_MARKER}. Edit freely — it is kept unless you pass --force.
# Durable/public ingress remains yours; --tunnel optionally adds an ephemeral Quick Tunnel service.
name: ${input.projectName}

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${input.port}:${input.port}"
    # The deployed environment's own declaration, read by the container itself. \`env_file\`, not per-name
    # \${NAME:-} interpolation: interpolation resolves from the SHELL or the project .env, which is exactly the
    # source a deployment must not have. A FIXED path, never the builder's FASTAGENT_SECRETS_DIR — this file is a
    # committed artifact and must mean the same thing on every machine. \`deploy\` creates it if it is missing.
    env_file:
      - ${DOCKER_VALUE_FILE}
    environment:
      PORT: "${input.port}"
      # Machinery on the ONE state volume: mutable state, credentials (logged in on the box) and the clones of the
      # agent's github content. Pinned AFTER env_file so a local path in that file (the scaffold lists these) cannot
      # send the container's state, sessions, credentials or clones somewhere outside the volume — or at a host path
      # that does not exist here at all.
      FASTAGENT_STATE_DIR: "${MOUNT}/.state"
      FASTAGENT_SECRETS_DIR: "${MOUNT}/.secrets"
      FASTAGENT_AUTH_PATH: "${MOUNT}/.secrets/auth.json"
      FASTAGENT_CONTEXTS_DIR: "${MOUNT}/.contexts"
    volumes:
      - state:${MOUNT}
    # The agent's log is where a failure's reason is recorded (a scheduled fire logs the detail; what the turn
    # SAID is in its session, not here), and Docker's default json-file driver never rotates — so on this host
    # the bound has to be written down. Fly and Railway bound their own log retention; AgentCore does NOT
    # (CloudWatch keeps data indefinitely until an operator sets a retention policy — its runbook says so).
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
${tunnelService}
volumes:
  state:
`;
}

/** Compute local-Docker artifacts + the runbook; no Docker process is touched here. */
export function planDockerDeploy(input: DockerPlanInput): DockerPlan {
  const composePath = DOCKER_COMPOSE_FILE;
  const artifacts: Artifact[] = [{ path: composePath, content: composeYaml(input) }, ...containerArtifacts(input)];
  // One spelling for every command: the generated file names the value file itself (`env_file`), so no command
  // needs a flag to reach the deployed environment's declaration.
  const compose = `docker compose -f ${composePath}`;
  const secrets = input.secrets ?? [];
  const paths = webhookPaths(input.channels);

  const runbook: string[] = [
    `# Run FastAgent in local Docker. ${composePath} / Dockerfile(.dockerignore) are generated above.`,
    `# Existing artifacts are authoritative and kept; edit Dockerfile or ${composePath} freely.`,
    `# Prereqs: Docker Engine/Desktop with Compose >= ${MIN_DOCKER_COMPOSE_VERSION} (\`docker compose version\`).`,
  ];

  if (secrets.length > 0) {
    runbook.push(
      `# Environment: the container reads ${input.valueFile} whole (Compose \`env_file\`) — that file declares the`,
      `# deployed environment (in CI, write it before running the command):`,
      ...secrets.map((secret) => `#   ${secret.name}: ${secret.hint}`),
    );
  }
  runbook.push(
    `# Run from the agent directory. The build bakes it as the definition and installs its`,
    `# package.json dependencies.`,
  );

  runbook.push(
    ``,
    `# Before building a new definition release, run \`fastagent deploy docker\` to refresh its manifest.`,
    `# The Compose volume at ${MOUNT} retains the deployed definition, state and credentials.`,
    `${compose} up -d --build`,
    `curl --fail http://127.0.0.1:${input.port}/health`,
    ...(input.boxLogin
      ? [
          `# Model auth: once it is up, the deployment logs in to ${input.boxLogin} itself:`,
          `${deploymentLoginCommand("docker", input.boxLogin)}`,
        ]
      : []),
    ``,
    `# Operate it:`,
    `${compose} logs -f agent`,
    `${compose} ps`,
    `${compose} down        # stops containers; keeps the state volume`,
    `# ${compose} down -v   # DESTRUCTIVE: deletes credentials and all agent state`,
  );

  if (input.tunnel) {
    runbook.push(
      ``,
      `# Quick Tunnel: \`--run\` starts the Compose tunnel service and reads its ephemeral public URL.`,
      `# Telegram/Feishu/Lark and locally onboarded Slack auto-register; manual Slack prints its console URL. Re-run after the`,
      `# tunnel container/Docker daemon restarts: a new Quick Tunnel URL must replace the old webhook URL.`,
      `${compose} logs -f tunnel`,
    );
  } else if (paths.length > 0) {
    runbook.push(
      ``,
      `# Public ingress is operator-owned: add your tunnel/proxy/DNS/TLS, then configure the`,
      `# detected default endpoint(s): ${paths.map((path) => `https://<your-domain>${path}`).join(", ")}.`,
      `# If your channels/*.ts glue remaps a route, use that path instead.`,
    );
  }

  runbook.push(
    `# Keep one agent replica: the local state volume is single-process; multiple replicas split/corrupt state.`,
  );

  return { artifacts, composePath, runbook };
}
