/** `fastagent deploy docker` — the local-Docker plan. */
import type { DeclaredChannel } from "../../channels/discover.ts";
import { webhookPaths } from "../channel-ingress.ts";
import { type Artifact, type ContainerInput, containerArtifacts } from "../container.ts";
import { deploymentSecrets, isEnvKey } from "../secrets.ts";
import { SECRETS_DIRNAME } from "../../paths.ts";
import type { DeclaredSecret } from "../../declared-secrets.ts";

export interface DockerPlanInput extends ContainerInput {
  /** Stable Compose project name, sanitized by {@link toDockerProjectName}. */
  projectName: string;
  /** Container + default host port. */
  port: number;
  /** What satisfies model auth locally: an env-var name, an OAuth/stored label, or undefined. */
  modelAuth: string | undefined;
  /** Every declared channel and its ingress — the source of the secret list and the ingress note. */
  channels: readonly DeclaredChannel[];
  /** Generate an optional Cloudflare Quick Tunnel service in Compose. */
  tunnel: boolean;
  /** Everything the definition declared it needs (deploy.secrets + tool/schedule declarations). */
  extraSecrets?: readonly DeclaredSecret[];
  /** The value file as the pre-flight resolved it (it follows `FASTAGENT_SECRETS_DIR`), workspace-relative. */
  valueFile: string;
}

export interface DockerPlan {
  /** fastagent.compose.yml + the shared Dockerfile/ignore artifacts. */
  artifacts: Artifact[];
  /** Compose file path relative to the workspace root (under the agent prefix). */
  composePath: string;
  /** Ordered local build/run/operate instructions. */
  runbook: string[];
}

const MOUNT = "/data";
const DOCKER_COMPOSE_FILE = "fastagent.compose.yml";
const GENERATED_COMPOSE_MARKER = "# Generated by `fastagent deploy docker`";
export const MIN_DOCKER_COMPOSE_VERSION = "2.3.3";
/** Pinned: generated deployment artifacts must not silently move when Cloudflare publishes `latest`. */
export const CLOUDFLARED_IMAGE = "cloudflare/cloudflared:2026.7.1";

/** Whether a Compose file still opts into generated-drift warnings (drop the marker after taking ownership). */
export function isGeneratedCompose(content: string): boolean {
  return content.startsWith(GENERATED_COMPOSE_MARKER);
}

/** Whether an authoritative Compose file already carries the generated tunnel service contract. */
export function composeHasTunnelService(content: string): boolean {
  return /^[ \t]+tunnel:\s*(?:#.*)?$/m.test(content);
}

/** Compose project names are lowercase [a-z0-9_-] and must start with an alphanumeric character. */
export function toDockerProjectName(directoryName: string): string {
  const slug = directoryName
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "")
    .slice(0, 54)
    .replace(/[-_]+$/g, "");
  return `fastagent-${slug || "agent"}`;
}

/** `${NAME:-}` without making JavaScript treat it as interpolation. */
function composeInterpolation(name: string): string {
  return `\${${name}:-}`;
}

function composeYaml(input: DockerPlanInput): string {
  // Compose sits beside the Dockerfile, under the agent prefix; the build context is always the WORKSPACE, so it
  // climbs back out of the one-level prefix deploy requires.
  const context = "..";
  const dockerfile = `${input.agentPrefix}Dockerfile`;
  const tunnelService = input.tunnel
    ? `
  # Cloudflare Quick Tunnel: ephemeral URL, generated only with \`deploy docker --tunnel\`.
  # No restart policy on purpose: a new process gets a new URL and needs webhook re-registration.
  tunnel:
    image: ${CLOUDFLARED_IMAGE}
    command:
      - tunnel
      - --no-autoupdate
      - --url
      - http://agent:${input.port}
    depends_on:
      - agent
    environment:
      # Docker Desktop may inject HTTP(S)_PROXY into containers. The origin is Docker-internal and must
      # bypass it; preserve any operator NO_PROXY entries after the required service/loopback names.
      NO_PROXY: "agent,localhost,127.0.0.1,${composeInterpolation("NO_PROXY")}"
      no_proxy: "agent,localhost,127.0.0.1,${composeInterpolation("no_proxy")}"
    restart: "no"
`
    : "";

  return `${GENERATED_COMPOSE_MARKER}. Edit freely — it is kept unless you pass --force.
# Durable/public ingress remains yours; --tunnel optionally adds an ephemeral Quick Tunnel service.
name: ${input.projectName}

services:
  agent:
    build:
      context: ${context}
      dockerfile: ${dockerfile}
    ports:
      - "127.0.0.1:${input.port}:${input.port}"
    # The deployed environment's own declaration, read by the container itself. \`env_file\`, not per-name
    # \${NAME:-} interpolation: interpolation resolves from the SHELL or the project .env, which is exactly the
    # source a deployment must not have. A FIXED path, never the builder's FASTAGENT_SECRETS_DIR — this file is a
    # committed artifact and must mean the same thing on every machine. \`deploy\` creates it if it is missing.
    env_file:
      - ${SECRETS_DIRNAME}/.env
    environment:
      PORT: "${input.port}"
      # Machinery on the ONE state volume: mutable state and (seeded, possibly rotated) secrets. Pinned AFTER
      # env_file so a local path in that file (the scaffold lists these) cannot send the container's state, sessions
      # or credentials somewhere outside the volume — or at a host path that does not exist here at all.
      FASTAGENT_STATE_DIR: "${MOUNT}/.state"
      FASTAGENT_SECRETS_DIR: "${MOUNT}/.secrets"
      FASTAGENT_SESSIONS_DIR: "${MOUNT}/.state/sessions"
      FASTAGENT_AUTH_PATH: "${MOUNT}/.secrets/auth.json"
      # The ONE value that is not in the value file: \`--run\` mints it from the local auth.json. Left as a seam in
      # the committed topology so a hand-run \`up\` can supply it the same way — from the ENVIRONMENT of that \`up\`.
      # Writing this one key into the value file does nothing: \`environment:\` is applied after \`env_file\`, so the
      # line below would blank it and the container would start without seeding auth.json.
      FASTAGENT_AUTH_SEED: "${composeInterpolation("FASTAGENT_AUTH_SEED")}"
    volumes:
      - state:${MOUNT}
    restart: unless-stopped
${tunnelService}
volumes:
  state:
`;
}

/** Compute local-Docker artifacts + the runbook; no Docker process is touched here. */
export function planDockerDeploy(input: DockerPlanInput): DockerPlan {
  const composePath = `${input.agentPrefix}${DOCKER_COMPOSE_FILE}`;
  const artifacts: Artifact[] = [{ path: composePath, content: composeYaml(input) }, ...containerArtifacts(input)];
  // One spelling for every command: the generated file names the value file itself (`env_file`), so no command
  // needs a flag to reach the deployed environment's declaration.
  const compose = `docker compose -f ${composePath}`;
  const secrets = deploymentSecrets(input.modelAuth, input.channels, input.extraSecrets);
  const required = secrets.filter((secret) => secret.required);
  const optional = secrets.filter((secret) => !secret.required);
  const paths = webhookPaths(input.channels);

  const runbook: string[] = [
    `# Run FastAgent in local Docker. ${composePath} / Dockerfile(.dockerignore) are generated above.`,
    `# Existing artifacts are authoritative and kept; edit Dockerfile or ${composePath} freely.`,
    `# Prereqs: Docker Engine/Desktop with Compose >= ${MIN_DOCKER_COMPOSE_VERSION} (\`docker compose version\`).`,
  ];

  if (required.length > 0) {
    runbook.push(
      `# Required environment values. Put them in ${input.valueFile} — that file declares the deployed`,
      `# environment (in CI, write it before running the command):`,
      ...required.map((secret) => `#   ${secret.name}: ${secret.hint}`),
    );
  }
  if (optional.length > 0) {
    runbook.push(`# Optional environment values:`, ...optional.map((secret) => `#   ${secret.name}: ${secret.hint}`));
  }
  if (!isEnvKey(input.modelAuth)) {
    runbook.push(
      input.modelAuth === undefined
        ? `# Model auth: none found locally — run \`fastagent login\` or set a provider API key before --run.`
        : `# Model auth: local source is "${input.modelAuth}" — \`--run\` carries auth.json as FASTAGENT_AUTH_SEED.`,
      `# For a manual Compose run, provide a provider API key or set FASTAGENT_AUTH_SEED yourself.`,
    );
  }

  runbook.push(
    `# Run from the WORKSPACE ROOT (the directory containing ${input.agentPrefix}).`,
    `# The build bakes the whole directory as the agent's workspace; only the agent's own`,
    `# dependencies (${input.agentPrefix}package.json) are installed.`,
  );

  runbook.push(
    ``,
    `# Before building a new definition release, run \`fastagent deploy docker\` to refresh its manifest.`,
    `# The Compose volume at ${MOUNT} retains the workspace, state and credentials.`,
    `${compose} up -d --build`,
    `curl --fail http://127.0.0.1:${input.port}/health`,
    ``,
    `# Operate it:`,
    `${compose} logs -f agent`,
    `${compose} ps`,
    `${compose} down        # stops containers; keeps the state volume`,
    `# ${compose} down -v   # DESTRUCTIVE: deletes workspace, credentials and all agent state`,
  );

  if (input.tunnel) {
    runbook.push(
      ``,
      `# Quick Tunnel: \`--run\` starts the Compose tunnel service and reads its ephemeral public URL.`,
      `# Telegram/Feishu/Lark and locally onboarded Slack auto-register; GitHub/manual Slack print console URLs. Re-run after the`,
      `# tunnel container/Docker daemon restarts: a new Quick Tunnel URL must replace the old webhook URL.`,
      `${compose} logs -f tunnel`,
    );
  } else if (paths.length > 0) {
    runbook.push(
      ``,
      `# Public ingress is operator-owned: add your tunnel/proxy/DNS/TLS, then configure the`,
      `# detected default endpoint(s): ${paths.map((path) => `https://<your-domain>${path}`).join(", ")}.`,
      `# If your channels/*.ts glue remaps a route, use that path instead.`,
    );
  }

  runbook.push(
    `# Keep one agent replica: the local state volume is single-process; multiple replicas split/corrupt state.`,
  );

  return { artifacts, composePath, runbook };
}
