/** The portable container — Dockerfile + .dockerignore, host-neutral. */
import { SECRETS_DIRNAME, STATE_DIRNAME } from "../paths.ts";
import { RELEASE_FILE, parseDeploymentRelease, type DeploymentRelease } from "./workspace.ts";

export interface Artifact {
  path: string;
  content: string;
}

/** Fixed first-line prefix of a fastagent-generated Dockerfile. */
export const GENERATED_DOCKERFILE_MARKER = "# Generated by `fastagent deploy`";

/** The ONE predicate for "did fastagent generate this Dockerfile?". */
export function isGeneratedDockerfile(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERFILE_MARKER);
}

/**
 * First line of a generated `.dockerignore` — and, for the workspace-root one, the single artifact deploy writes
 * outside the agent dir.
 */
const GENERATED_DOCKERIGNORE_MARKER = "# Generated by `fastagent deploy`";

export function isGeneratedDockerignore(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERIGNORE_MARKER);
}

export interface ContainerInput {
  /** Stable for one release; generated once by the deploy preflight, never on container restart. */
  releaseId: string;
  /** Whether the agent has a package.json (a code agent); else a pure markdown/skills agent. */
  hasPackageJson: boolean;
  /** The package manager the generated image targets. */
  runtime: "node" | "bun";
  /** Whether the runtime's lockfile exists (package-lock.json for npm, bun.lock/bun.lockb for bun). */
  hasLockfile: boolean;
  /** For `runtime: "bun"`, the `FROM oven/bun:<tag>` version (from packageManager `bun@x`), else `"1"`. */
  bunVersion?: string;
  /** This fastagent version, to PIN the global install on the markdown path (reproducible redeploys). */
  version: string;
  /** Extra apt packages (fastagent.config deploy.apt) baked in for the agent's tools — git, ripgrep, …. */
  apt?: string[];
  /**
   * The model this deployment resolved, recorded in the release manifest — set only when the deployed environment's
   * VALUE FILE named it (a `config.model` needs nothing: the config ships too). The manifest is the carrier because
   * it is rebuilt and rewritten on every deploy, so the answer cannot go stale, and nothing on the way in can
   * interpolate the operator's shell.
   */
  modelSpec?: string;
  /**
   * Where deploy's artifacts and the agent's own files sit, relative to the BUILD CONTEXT (which is always the
   * workspace).
   */
  agentPrefix: string;
  /** Workspace-relative machinery paths the NAME-based excludes below would miss. */
  machineryPaths?: string[];
  /** Whether the baked workspace ships a `.git` (preflight fact). */
  shipsGit?: boolean;
}

/** The apt layer (cached right after FROM). */
function aptLayer(packages?: string[]): string {
  return packages && packages.length > 0
    ? `RUN apt-get update \\
 && apt-get install -y --no-install-recommends ${packages.join(" ")} \\
 && rm -rf /var/lib/apt/lists/*
`
    : "";
}

function dockerfile(input: ContainerInput): string {
  // The whole workspace is baked at /app; deps install (and the local bin lives) under the agent, which deploy
  // requires to be a SUBDIRECTORY of it (preflight gates a flat layout, containerArtifacts re-asserts it), so the
  // prefix is never empty.
  const prefix = input.agentPrefix;
  const dir = prefix.replace(/\/$/, "");
  const into = (p: string): string => `${prefix}${p}`;
  // A build step that must run IN the agent dir (`RUN` already gets a shell from docker).
  const at = (cmd: string): string => `cd ${dir} && ${cmd}`;
  // The entrypoint.
  const bunCmd = `["sh", "-c", "cd ${dir} && exec bun run fastagent start /app"]`;
  const layoutNote = `The whole directory is the agent's workspace; the agent itself lives in ${prefix}`;
  // apt layer right after FROM (cached across code changes): the agent's tools may shell out to git etc., which
  // node:22-slim lacks.
  const apt = aptLayer(input.apt);
  // PIN the agent into the image.
  const pin = `ENV FASTAGENT_AGENT=${dir}\n`;
  // The caches stay off the volume: they are rebuildable, and a host mount is the slow disk.
  const deployment = `ENV FASTAGENT_RELEASE_FILE=/app/${into(RELEASE_FILE)}\nENV FASTAGENT_STORAGE_DIR=/data\nENV npm_config_cache=/tmp/fastagent/npm\nENV BUN_INSTALL_CACHE_DIR=/tmp/fastagent/bun\n`;
  // No package.json → pure markdown/skills agent: install the pinned CLI GLOBALLY and run `fastagent` from PATH.
  if (!input.hasPackageJson) {
    return `${GENERATED_DOCKERFILE_MARKER}. ${layoutNote}
# npm-based (a markdown/skills agent installs the pinned CLI globally; node:22-slim has npm).
FROM node:22-slim
${apt}WORKDIR /app
${deployment}${pin}RUN npm i -g @fastagent-sh/fastagent@${input.version}
COPY . .
CMD ["fastagent", "start", "/app"]
`;
  }
  const isBun = input.runtime === "bun";
  const base = isBun ? `oven/bun:${input.bunVersion ?? "1"}` : "node:22-slim";
  const note = isBun
    ? "# Bun-based (packageManager: bun / a bun lockfile detected). fastagent runs under Bun (bun run)."
    : "# npm-based — for pnpm/yarn, adapt the install line + the lockfile COPY (corepack enable, etc.).";
  const head = `${GENERATED_DOCKERFILE_MARKER}. ${layoutNote}
${note}
FROM ${base}
${apt}WORKDIR /app
${deployment}${pin}`;
  // Install ALL deps (no --omit=dev / --production): a repo-as-agent (e.g. an Astro site it operates on) needs its
  // full toolchain.
  if (isBun) {
    // `--frozen-lockfile` needs bun.lock and hard-fails without it.
    const install = input.hasLockfile ? "bun install --frozen-lockfile" : "bun install";
    return `${head}COPY ${into("package.json")} ${into("bun.lock*")} ./${prefix}
RUN ${at(install)}
COPY . .
CMD ${bunCmd}
`;
  }
  // `npm ci` requires a lockfile and hard-fails without one (a common `init --no-install` agent); fall back to `npm
  // install` when there is none so the build never breaks.
  const install = input.hasLockfile ? "npm ci" : "npm install";
  return `${head}COPY ${into("package.json")} ${into("package-lock.json*")} ./${prefix}
RUN ${at(install)}
COPY . .
CMD ["./${into("node_modules/.bin/fastagent")}", "start", "/app"]
`;
}

/** Patterns are RECURSIVE (`**​/`) on purpose. */
const dockerignore = (input: ContainerInput): string =>
  DOCKERIGNORE_BASE +
  (input.machineryPaths ?? [])
    // Skip what the name-based rules above already cover: the default `<agent>/.secrets` / `<agent>/.state` and
    // anything inside them.
    .filter((p) =>
      [`${input.agentPrefix}${SECRETS_DIRNAME}`, `${input.agentPrefix}${STATE_DIRNAME}`].every(
        (covered) => p !== covered && !p.startsWith(`${covered}/`),
      ),
    )
    .map(
      (p) => `# resolved machinery path (FASTAGENT_SECRETS_DIR / FASTAGENT_AUTH_PATH / FASTAGENT_STATE_DIR)\n/${p}\n`,
    )
    .join("");

const DOCKERIGNORE_BASE = `${GENERATED_DOCKERIGNORE_MARKER}. Delete this line to take ownership (deploy then keeps your file).
**/node_modules
**/${SECRETS_DIRNAME}/**
**/${STATE_DIRNAME}
**/.cache
**/.env
**/.env.*
!**/.env.example
!**/${SECRETS_DIRNAME}/.gitignore
**/*.log
# .git is deliberately shipped: the agent can pull to freshen content and push its work back
# (the generated image installs the git binary when this directory ships a .git; otherwise
# add deploy.apt ["git"]). For a smaller image with no git needs, add a ".git" line here.
`;

/** The Dockerfile + ignore artifacts — spread into any host's artifact list. */
export function containerArtifacts(input: ContainerInput): Artifact[] {
  if (!input.agentPrefix)
    throw new Error("deploy requires a nested agent: point deploy at the workspace containing fastagent/");
  const ignore = dockerignore(input);
  const release: DeploymentRelease = {
    version: 1,
    id: input.releaseId,
    agent: input.agentPrefix.replace(/\/$/, ""),
    ...(input.modelSpec !== undefined ? { model: input.modelSpec } : {}),
  };
  parseDeploymentRelease(JSON.stringify(release));
  return [
    { path: `${input.agentPrefix}${RELEASE_FILE}`, content: `${JSON.stringify(release, null, 2)}\n` },
    { path: `${input.agentPrefix}Dockerfile`, content: dockerfile(input) },
    { path: ".dockerignore", content: ignore },
    { path: `${input.agentPrefix}Dockerfile.dockerignore`, content: ignore },
  ];
}
