/** The portable container — Dockerfile + .dockerignore, host-neutral. */
import { CONTENT_DIRNAME, SECRETS_DIRNAME, STATE_DIRNAME } from "../paths.ts";
import { DEPLOYED_DEFINITION_DIR, RELEASE_FILE, parseDeploymentRelease, type DeploymentRelease } from "./workspace.ts";
import { type DeclaredEnvironment, MISE_FILE, MISE_LOCK_FILE } from "../environment/declare.ts";
import { isolationAt } from "../environment/mise.ts";

export interface Artifact {
  path: string;
  content: string;
}

/** The result line for a box CLI that refused `login --stdio` as an unknown option (see {@link boxLoginCommand}). */
const STDIO_PREDATED = JSON.stringify({
  type: "result",
  ok: false,
  reason: "failed",
  message:
    "the fastagent installed in the agent on the box predates login --stdio: align the @fastagent-sh/fastagent " +
    "version in the agent package.json with the CLI that deploys it, then redeploy",
}).replaceAll('"', '\\"');

/** Where a generated image keeps its storage (`FASTAGENT_STORAGE_DIR`); every host mounts its volume here. */
const STORAGE_DIR = "/data";

/** Where a generated image holds the definition: the build context, which is the agent directory. */
export const IMAGE_DEFINITION_DIR = "/app/definition";

/**
 * The shell command that runs `fastagent login --stdio <args>` inside a running generated image, as the server there
 * would see it: in the deployed agent directory, with the storage and credential paths resolved by the same defaults
 * `prepareStartWorkspace` applies. A host's own shell does not reliably hand those over — its session may not start
 * in the server's directory, and the platform's variables are the only ones it inherits. `storage` names the root
 * outright for a shell that inherits none of them. The CLI is the one the server runs: the agent's own install when
 * it has one (under Bun when the image is Bun's), else the pinned global.
 *
 * That own install may predate `login --stdio` (an agent pinned to an older release, deployed by a newer CLI). It then
 * refuses the flag as a usage error, exit 2, which a `login --stdio` that ran never gives (it answers 0 or 1 after its
 * result line), so the command answers for it: one result line naming the mismatch, instead of a shell that ended
 * with nothing to say. No quote or backtick in it: hosts wrap this whole line in `sh -c '…'`.
 */
export function boxLoginCommand(args: readonly string[], storage?: string): string {
  for (const value of [...args, ...(storage ? [storage] : [])]) {
    if (!/^[\w.@/-]+$/.test(value)) throw new Error(`cannot pass ${JSON.stringify(value)} to a shell on the box`);
  }
  return [
    ...(storage
      ? [`root="${storage}"`, `export FASTAGENT_SECRETS_DIR="$root/.secrets"`]
      : [
          `root="\${FASTAGENT_STORAGE_DIR:-${STORAGE_DIR}}"`,
          `export FASTAGENT_SECRETS_DIR="\${FASTAGENT_SECRETS_DIR:-$root/.secrets}"`,
        ]),
    `cd "$root/${DEPLOYED_DEFINITION_DIR}" || exit 1`,
    `f=fastagent`,
    `if [ -x node_modules/.bin/fastagent ]; then f=node_modules/.bin/fastagent; if command -v bun >/dev/null; then f="bun run fastagent"; fi; fi`,
    `$f login --stdio ${args.join(" ")}`,
    `code=$?`,
    `if [ $code -eq 2 ]; then printf "%s\\n" "${STDIO_PREDATED}"; fi`,
    `exit $code`,
  ].join("; ");
}

/** Fixed first-line prefix of a fastagent-generated Dockerfile. */
export const GENERATED_DOCKERFILE_MARKER = "# Generated by `fastagent deploy`";

/** The ONE predicate for "did fastagent generate this Dockerfile?". */
export function isGeneratedDockerfile(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERFILE_MARKER);
}

/** First line of a generated `.dockerignore`. */
const GENERATED_DOCKERIGNORE_MARKER = "# Generated by `fastagent deploy`";

export function isGeneratedDockerignore(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERIGNORE_MARKER);
}

export interface ContainerInput {
  /** Stable for one release; generated once by the deploy preflight, never on container restart. */
  releaseId: string;
  /** Whether the agent has a package.json (a code agent); else a pure markdown/skills agent. */
  hasPackageJson: boolean;
  /** The package manager the generated image targets. */
  runtime: "node" | "bun";
  /** Whether the runtime's lockfile exists (package-lock.json for npm, bun.lock/bun.lockb for bun). */
  hasLockfile: boolean;
  /** For `runtime: "bun"`, the `FROM oven/bun:<tag>` version (from packageManager `bun@x`), else `"1"`. */
  bunVersion?: string;
  /** This fastagent version, to PIN the global install on the markdown path (reproducible redeploys). */
  version: string;
  /** The Debian packages FastAgent itself needs in the image: git for content and a shipped `.git`, CA certificates for mise. */
  apt?: string[];
  /** The environment the agent declares (mise.toml), which the image installs with the agent's own mise. */
  environment?: Pick<DeclaredEnvironment, "tools" | "packages">;
  /**
   * The model this deployment resolved, recorded in the release manifest — set only when the deployed environment's
   * VALUE FILE named it (a `config.model` needs nothing: the config ships too). The manifest is the carrier because
   * it is rebuilt and rewritten on every deploy, so the answer cannot go stale, and nothing on the way in can
   * interpolate the operator's shell.
   */
  modelSpec?: string;
  /** The agent's name, recorded in the release manifest: the agent directory's own name. */
  agent: string;
  /** Agent-dir-relative machinery paths the NAME-based excludes below would miss. */
  machineryPaths?: string[];
  /** Whether the agent directory ships a `.git` (preflight fact). */
  shipsGit?: boolean;
}

/** Whether the image has git: FastAgent installs it for its own needs, or the agent declares it in mise.toml. */
export function imageHasGit(input: Pick<ContainerInput, "apt" | "environment">): boolean {
  return input.apt?.includes("git") === true || input.environment?.packages.includes("apt:git") === true;
}

/** The apt layer (cached right after FROM). */
function aptLayer(packages?: string[]): string {
  return packages && packages.length > 0
    ? `RUN apt-get update \\
 && apt-get install -y --no-install-recommends ${packages.join(" ")} \\
 && rm -rf /var/lib/apt/lists/*
`
    : "";
}

/** mise's own directories for the build, thrown away with the layer: nothing of them is read at run time. */
const BUILD_MISE_DIR = "/tmp/mise";

/**
 * The layers that install the agent's environment, after its dependencies (the agent's own mise among them) and before
 * the definition, so they stay cached while the definition changes. System packages first: a tool may link against
 * one. mise runs `apt-get install` without `--no-install-recommends`, so apt is told to skip them instead. The tools go
 * to mise's system directory (`--system`, /usr/local/share/mise/installs), which every mise reads beside its own data
 * directory: a deployed start points that one at the storage, where the tools the agent adds outlive the container.
 */
function environmentLayers(dir: string, environment: Pick<DeclaredEnvironment, "tools" | "packages">): string {
  const packages = environment.packages.length > 0;
  // mise writes no lock for a file without tools.
  const tools = environment.tools.length > 0;
  if (!packages && !tools) return "";
  const isolation = Object.entries(isolationAt(dir))
    .map(([key, value]) => `${key}=${value}`)
    .join(" ");
  // The agent's own mise, by its package: the bin link is not reliable (mise.ts `miseBinary`).
  const mise = `node_modules/@jdxcode/mise-linux-$(case "$(uname -m)" in aarch64|arm64) echo arm64;; *) echo x64;; esac)/bin/mise`;
  const steps = [
    ...(packages
      ? [
          `printf 'APT::Install-Recommends "false";\\nAPT::Install-Suggests "false";\\n' > /etc/apt/apt.conf.d/99-fastagent-environment`,
        ]
      : []),
    `export ${isolation} MISE_DATA_DIR=${BUILD_MISE_DIR} MISE_CACHE_DIR=${BUILD_MISE_DIR}/cache MISE_STATE_DIR=${BUILD_MISE_DIR}/state MISE="${mise}"`,
    ...(packages ? [`"$MISE" bootstrap packages apply --yes`, "rm -rf /var/lib/apt/lists/*"] : []),
    ...(tools ? [`"$MISE" --locked install --system`] : []),
    `rm -rf ${BUILD_MISE_DIR}`,
  ];
  return `COPY ${MISE_FILE}${tools ? ` ${MISE_LOCK_FILE}` : ""} ./
RUN ${steps.join(" \\\n && ")}
`;
}

function dockerfile(input: ContainerInput): string {
  // The build context is the agent directory, baked at IMAGE_DEFINITION_DIR; deps install (and the local bin lives)
  // there.
  const dir = IMAGE_DEFINITION_DIR;
  const layoutNote = `The agent directory is baked at ${dir}`;
  // apt layer right after FROM (cached across code changes): the agent's tools may shell out to git etc., which
  // node:22-slim lacks.
  const apt = aptLayer(input.apt);
  // The caches stay off the volume: they are rebuildable, and a host mount is the slow disk.
  const deployment = `ENV FASTAGENT_RELEASE_FILE=${dir}/${RELEASE_FILE}\nENV FASTAGENT_STORAGE_DIR=${STORAGE_DIR}\nENV npm_config_cache=/tmp/fastagent/npm\nENV BUN_INSTALL_CACHE_DIR=/tmp/fastagent/bun\n`;
  // No package.json → pure markdown/skills agent: install the pinned CLI GLOBALLY and run `fastagent` from PATH.
  if (!input.hasPackageJson) {
    return `${GENERATED_DOCKERFILE_MARKER}. ${layoutNote}
# npm-based (a markdown/skills agent installs the pinned CLI globally; node:22-slim has npm).
FROM node:22-slim
${apt}WORKDIR ${dir}
${deployment}RUN npm i -g @fastagent-sh/fastagent@${input.version}
COPY . .
CMD ["fastagent", "start", "${dir}"]
`;
  }
  const environment = input.environment ? environmentLayers(dir, input.environment) : "";
  const isBun = input.runtime === "bun";
  const base = isBun ? `oven/bun:${input.bunVersion ?? "1"}` : "node:22-slim";
  const note = isBun
    ? "# Bun-based (packageManager: bun / a bun lockfile detected). fastagent runs under Bun (bun run)."
    : "# npm-based — for pnpm/yarn, adapt the install line + the lockfile COPY (corepack enable, etc.).";
  const head = `${GENERATED_DOCKERFILE_MARKER}. ${layoutNote}
${note}
FROM ${base}
${apt}WORKDIR ${dir}
${deployment}`;
  // Install ALL deps (no --omit=dev / --production): an agent's tools may need its full toolchain.
  //
  // `*.tgz` RIDES ALONG with the manifest, because the install layer runs BEFORE `COPY . .` and a
  // `"dep": "file:./something.tgz"` resolves against the directory it is installing in. Without this the file is
  // not there yet and the build fails on a dependency the author can see sitting in the agent directory. It is
  // also what lets a live probe deploy the CHECKOUT (`npm pack` output) rather than the published release.
  if (isBun) {
    // `--frozen-lockfile` needs bun.lock and hard-fails without it.
    const install = input.hasLockfile ? "bun install --frozen-lockfile" : "bun install";
    return `${head}COPY package.json bun.lock* *.tgz ./
RUN ${install}
${environment}COPY . .
CMD ["bun", "run", "fastagent", "start", "${dir}"]
`;
  }
  // `npm ci` requires a lockfile and hard-fails without one (a common `init --no-install` agent); fall back to `npm
  // install` when there is none so the build never breaks.
  const install = input.hasLockfile ? "npm ci" : "npm install";
  return `${head}COPY package.json package-lock.json* *.tgz ./
RUN ${install}
${environment}COPY . .
CMD ["./node_modules/.bin/fastagent", "start", "${dir}"]
`;
}

/** Patterns are RECURSIVE (`**​/`) on purpose. */
const dockerignore = (input: ContainerInput): string =>
  DOCKERIGNORE_BASE +
  (input.machineryPaths ?? [])
    // Skip what the name-based rules above already cover: the default `.secrets` / `.state` and anything inside them.
    .filter((p) => [SECRETS_DIRNAME, STATE_DIRNAME].every((covered) => p !== covered && !p.startsWith(`${covered}/`)))
    .map(
      (p) => `# resolved machinery path (FASTAGENT_SECRETS_DIR / FASTAGENT_AUTH_PATH / FASTAGENT_STATE_DIR)\n/${p}\n`,
    )
    .join("");

const DOCKERIGNORE_BASE = `${GENERATED_DOCKERIGNORE_MARKER}. Delete this line to take ownership (deploy then keeps your file).
**/node_modules
**/${SECRETS_DIRNAME}/**
**/${STATE_DIRNAME}
/${CONTENT_DIRNAME}
**/.cache
**/.env
**/.env.*
!**/.env.example
!**/${SECRETS_DIRNAME}/.gitignore
**/*.log
# .git is deliberately shipped with the definition (the generated image installs the git binary
# when this directory ships a .git; otherwise declare apt:git in mise.toml). For a smaller image with no
# git needs, add a ".git" line here.
`;

/** The Dockerfile + ignore artifacts — spread into any host's artifact list. */
export function containerArtifacts(input: ContainerInput): Artifact[] {
  const ignore = dockerignore(input);
  const release: DeploymentRelease = {
    version: 1,
    id: input.releaseId,
    agent: input.agent,
    ...(input.modelSpec !== undefined ? { model: input.modelSpec } : {}),
  };
  parseDeploymentRelease(JSON.stringify(release));
  return [
    { path: RELEASE_FILE, content: `${JSON.stringify(release, null, 2)}\n` },
    { path: "Dockerfile", content: dockerfile(input) },
    // Both names: BuildKit prefers the one beside the Dockerfile, the classic builder reads the context root's.
    { path: ".dockerignore", content: ignore },
    { path: "Dockerfile.dockerignore", content: ignore },
  ];
}
