/**
 * The portable container — Dockerfile + .dockerignore, host-neutral. Every deploy target ships these
 * unchanged; only the host config (fly.toml / railway.json) and the CLI sequence differ. The image
 * runs `fastagent start /app` on `$PORT` with state under `$FASTAGENT_STATE_DIR` — standard container
 * conventions, no host coupling. Extracted from the Fly plan when Railway became the second target.
 */

export interface Artifact {
  path: string;
  content: string;
}

/** Fixed first-line prefix of a fastagent-generated Dockerfile — the ONE source both the generator (the
 *  `head` below) and the "is this ours?" check (cli deploy's kept-Dockerfile apt warn) share, so they
 *  can't drift into detecting a marker the generator no longer writes. */
export const GENERATED_DOCKERFILE_MARKER = "# Generated by `fastagent deploy`";

/** The ONE predicate for "did fastagent generate this Dockerfile?" — a generated file opens with the
 *  marker, so a hand-written one (or a file where the marker was dropped to take ownership) reads false.
 *  Both the "keep vs flag-as-stale" decision and the apt warning share this; a split would let them
 *  disagree on the same file (e.g. a marker not at byte 0). */
export function isGeneratedDockerfile(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERFILE_MARKER);
}

export interface ContainerInput {
  /** Whether the workspace has a package.json (a code workspace); else a pure markdown/skills agent. */
  hasPackageJson: boolean;
  /** Whether a package-lock.json exists — `npm ci` needs it; without it the Dockerfile uses `npm install`. */
  hasLockfile: boolean;
  /** This fastagent version, to PIN the global install on the markdown path (reproducible redeploys). */
  version: string;
  /** Extra apt packages (fastagent.config deploy.apt) baked in for the agent's tools — git, ripgrep, …. */
  apt?: string[];
}

function dockerfile(input: ContainerInput): string {
  // apt layer right after FROM (cached across code changes): the agent's tools may shell out to git etc.,
  // which node:22-slim lacks. Debian default repos only — a package needing a custom repo (gh) or a
  // different base is the operator's own Dockerfile (kept if present). deploy.apt is package-name-validated.
  const apt =
    input.apt && input.apt.length > 0
      ? `RUN apt-get update \\
 && apt-get install -y --no-install-recommends ${input.apt.join(" ")} \\
 && rm -rf /var/lib/apt/lists/*
`
      : "";
  const head = `${GENERATED_DOCKERFILE_MARKER}. The directory IS the agent — no build step.
# npm-based — for pnpm/yarn, adapt the install line + the lockfile COPY (corepack enable, etc.).
FROM node:22-slim
${apt}WORKDIR /app
`;
  // No package.json → pure markdown/skills agent: install the CLI globally, PINNED for reproducible
  // redeploys (the code path is pinned by its lockfile; this path has no other lock).
  if (!input.hasPackageJson) {
    return `${head}RUN npm i -g @kid7st/fastagent@${input.version}
COPY . .
CMD ["fastagent", "start", "/app"]
`;
  }
  // `npm ci` requires a lockfile and hard-fails without one (a common `init --no-install` workspace);
  // fall back to `npm install` when there is none so the build never breaks. Caveat: `npm install`
  // resolves caret ranges at build time, so THIS branch is NOT reproducible — unlike the pinned
  // `npm ci` (lockfile) and pinned global (markdown) paths. The CLI warns to commit a lockfile.
  const install = input.hasLockfile ? "npm ci --omit=dev" : "npm install --omit=dev";
  return `${head}COPY package.json package-lock.json* ./
RUN ${install}
COPY . .
CMD ["npx", "fastagent", "start", "/app"]
`;
}

const DOCKERIGNORE = `node_modules
.fastagent
.env
.env.*
!.env.example
*.log
# .git is excluded to keep the image small. If your agent runs git on its OWN history
# (git log/blame over the repo it ships in), delete the next line so that history is in the image.
.git
`;

/** The Dockerfile + .dockerignore artifacts — spread into any host's artifact list. */
export function containerArtifacts(input: ContainerInput): Artifact[] {
  return [
    { path: "Dockerfile", content: dockerfile(input) },
    { path: ".dockerignore", content: DOCKERIGNORE },
  ];
}
