/**
 * `fastagent deploy fly` — the Fly.io deploy PLAN, computed from the resolved definition. Pure: facts
 * in, artifact contents + an ordered runbook out; the CLI (deploy side effects live there) writes the
 * files and prints the runbook.
 *
 * fastagent owns the two ends only it can know — generate definition-aware artifacts (state root →
 * volume, autostop tuned to the turn model, the exact secret list) and the post-deploy webhook step —
 * and GUIDES the middle (flyctl app/volume/secrets/deploy). The consumer is a coding agent that runs
 * flyctl itself; this hands it a precise, values-resolved runbook rather than running it. The runbook
 * is a FIRST-deploy sequence: `apps`/`volumes create` are one-time (marked so — re-running would make a
 * second volume, the state split it warns against); a redeploy is `fly deploy` alone.
 *
 * autostop = "suspend": the machine snapshots and suspends when idle (Fly Proxy sees inbound load 0),
 * resumes on the next webhook in ~hundreds of ms. A long turn interrupted by an idle-suspend whose
 * snapshot is discarded replays on the next start (the Telegram L1 turn store) — at-least-once, the
 * documented floor. State on the /data volume survives stop/suspend on the same machine.
 */
import { channelSetup, type ChannelKind } from "../scaffold/add-channel.ts";

export interface FlyPlanInput {
  /** Fly app name — globally unique, lowercase; the CLI sanitizes it from the dir basename. */
  appName: string;
  /** The port the app listens on (config.http.port ?? 8787); fly.toml routes to it. */
  port: number;
  /**
   * What satisfies model auth locally ({@link probeAuthSource}): an env-var name (`OPENAI_API_KEY`),
   * `"OAuth"`/`"stored credential"` (a local login the server can't use), or undefined (unconfigured).
   */
  modelAuth: string | undefined;
  /** Channels discovered in the workspace — each contributes its required secrets + webhook step. */
  channels: ChannelKind[];
  /** Whether the workspace has a package.json (a code workspace); else a pure markdown/skills agent. */
  hasPackageJson: boolean;
  /** Whether a package-lock.json exists — `npm ci` needs it; without it the Dockerfile uses `npm install`. */
  hasLockfile: boolean;
  /** This fastagent version, to PIN the global install on the markdown path (reproducible redeploys). */
  version: string;
  /** `auto_stop_machines` — `"suspend"` (default, fast resume) or `"stop"` (cold start). CLI `--stop`. */
  autostop: "suspend" | "stop";
  /** Allow scaling to zero when idle (default true → `min_machines_running=0`). CLI `--no-scale-to-zero`
   *  forces one machine up; a github channel forces it too (fire-and-forget turns have no replay). */
  scaleToZero: boolean;
}

export interface Artifact {
  path: string;
  content: string;
}

export interface FlyPlan {
  /** fly.toml / Dockerfile / .dockerignore — written by the CLI (skipped if present unless --force). */
  artifacts: Artifact[];
  /** The ordered, values-resolved deploy runbook — printed to stdout for the coding agent to execute. */
  runbook: string[];
}

/**
 * Is this local auth source an env-var API key (→ becomes a Fly secret) vs OAuth / stored / none?
 * Positive match on the UPPER_SNAKE env-var naming shape, NOT a negative exclude of today's sentinel
 * labels: a new non-env `AuthResult.source` (e.g. `keychain`) then degrades to guidance, never a fake
 * `keychain=<value>` secret — the two modules don't couple through an exhaustive string list.
 */
function isEnvKey(source: string | undefined): source is string {
  return source !== undefined && /^[A-Z][A-Z0-9_]*$/.test(source);
}

function flyToml(
  appName: string,
  port: number,
  hasGithub: boolean,
  autostop: "suspend" | "stop",
  scaleToZero: boolean,
): string {
  // min_machines_running: 1 (keep one up) when a github channel is present OR the operator opted out of
  // scale-to-zero. GitHub's is a SAFETY default — its fire-and-forget turns have no replay (unlike
  // Telegram's L1 turn store), so scaling to zero could drop an in-flight review; the extra capacity
  // still suspends, it just never takes the LAST machine down. Reason-tagged so the comment is honest.
  const min = hasGithub
    ? `  min_machines_running = 1         # github turns have no replay — don't scale to zero (an in-flight review would be lost)`
    : !scaleToZero
      ? `  min_machines_running = 1         # kept running (--no-scale-to-zero)`
      : `  min_machines_running = 0         # scale to zero`;
  const stopLine =
    autostop === "stop"
      ? `  auto_stop_machines = "stop"      # stop on idle (cold start on the next webhook)`
      : `  auto_stop_machines = "suspend"   # suspend on idle (fast resume on the next webhook)`;
  return `# Generated by \`fastagent deploy fly\`. Edit freely — it is not regenerated unless you pass --force.
app = "${appName}"
primary_region = "iad"  # set your region (list: \`fly platform regions\`)

[build]

[env]
  FASTAGENT_STATE_DIR = "/data"  # the ONE machine-state root — auth, sessions, channel state
  PORT = "${port}"

[http_service]
  internal_port = ${port}
  force_https = true
${stopLine}
  auto_start_machines = true
${min}

[mounts]
  source = "data"
  destination = "/data"            # FASTAGENT_STATE_DIR — persists across stop/suspend/redeploy

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"                 # suspend is not recommended above 2 GB
`;
}

function dockerfile(input: Pick<FlyPlanInput, "hasPackageJson" | "hasLockfile" | "version">): string {
  const head = `# Generated by \`fastagent deploy fly\`. The directory IS the agent — no build step.
# npm-based — for pnpm/yarn, adapt the install line + the lockfile COPY (corepack enable, etc.).
FROM node:22-slim
WORKDIR /app
`;
  // No package.json → pure markdown/skills agent: install the CLI globally, PINNED for reproducible
  // redeploys (the code path is pinned by its lockfile; this path has no other lock).
  if (!input.hasPackageJson) {
    return `${head}RUN npm i -g @kid7st/fastagent@${input.version}
COPY . .
CMD ["fastagent", "start", "/app"]
`;
  }
  // `npm ci` requires a lockfile and hard-fails without one (a common `init --no-install` workspace);
  // fall back to `npm install` when there is none so the build never breaks. Caveat: `npm install`
  // resolves caret ranges at build time, so THIS branch is NOT reproducible — unlike the pinned
  // `npm ci` (lockfile) and pinned global (markdown) paths. The CLI warns to commit a lockfile.
  const install = input.hasLockfile ? "npm ci --omit=dev" : "npm install --omit=dev";
  return `${head}COPY package.json package-lock.json* ./
RUN ${install}
COPY . .
CMD ["npx", "fastagent", "start", "/app"]
`;
}

const DOCKERIGNORE = `node_modules
.git
.fastagent
.env
.env.*
!.env.example
*.log
`;

/** Compute the Fly deploy plan from the resolved definition. */
export function planFlyDeploy(input: FlyPlanInput): FlyPlan {
  const { appName, port, modelAuth, channels } = input;
  const artifacts: Artifact[] = [
    {
      path: "fly.toml",
      content: flyToml(appName, port, channels.includes("github"), input.autostop, input.scaleToZero),
    },
    { path: "Dockerfile", content: dockerfile(input) },
    { path: ".dockerignore", content: DOCKERIGNORE },
  ];

  // The exact secret list the deployed machine needs, computed from the definition: the model key (when
  // local auth is an env key) + every discovered channel's secrets. Names + hints as COMMENT lines (a
  // `#` inside a `\`-continued command would break the shell), then one flat, executable `fly secrets
  // set` the coding agent fills — `<value>` placeholders, never inline comments.
  const secrets: { name: string; hint: string }[] = [];
  if (isEnvKey(modelAuth)) secrets.push({ name: modelAuth, hint: "your model provider key" });
  for (const kind of channels) {
    for (const e of channelSetup(kind).env) secrets.push({ name: e.name, hint: e.hint });
  }

  const runbook: string[] = [
    `# Deploy "${appName}" to Fly.io. fly.toml / Dockerfile / .dockerignore are generated above.`,
    `# Prereqs: flyctl installed (https://fly.io/docs/flyctl/install) and \`fly auth login\`.`,
    ``,
    `# One-time setup (skip on a redeploy — a second run makes a SECOND app/volume, splitting state).`,
    `# Fly app names are GLOBALLY unique: if this fails as taken, set a unique "app" in fly.toml and`,
    `# re-run \`fastagent deploy fly\` — the runbook follows fly.toml's app name.`,
    `fly apps create ${appName}`,
    `# volume persists FASTAGENT_STATE_DIR=/data (sessions, auth, channel state) across stop/suspend/redeploy.`,
    `# <region> MUST equal primary_region in fly.toml (a volume in another region can't mount) — fly.toml`,
    `# is the single source for the region; skip this if the volume exists (fly volumes list --app ${appName}):`,
    `fly volumes create data --app ${appName} --region <region> --size 1`,
  ];

  if (secrets.length > 0) {
    runbook.push(
      ``,
      `# Secrets (replace each <value>):`,
      ...secrets.map((s) => `#   ${s.name}: ${s.hint}`),
      `fly secrets set --app ${appName} ${secrets.map((s) => `${s.name}=<value>`).join(" ")}`,
    );
  }
  runbook.push(`fly deploy --app ${appName}`);

  // Model-auth guidance: an env key becomes a secret above. Otherwise the plan can't read the local
  // credential's VALUE to set as a secret — true for OAuth AND a stored API key (both are
  // `AuthResult.source` non-env labels), so the wording doesn't prejudge whether it's migratable.
  if (!isEnvKey(modelAuth)) {
    runbook.push(
      ``,
      modelAuth === undefined
        ? `# Model auth: none configured locally.`
        : `# Model auth: your local auth is "${modelAuth}" — the plan can't read its value to set as a secret.`,
      `#   Set your provider API key as a Fly secret (fly secrets set KEY=...), OR place auth.json on the /data volume.`,
    );
  }

  // The fastagent-only post-step: point each channel's webhook at the live URL. Only fastagent knows the routes.
  // The URLs below assume each channel's DEFAULT route key (POST /telegram, POST /webhook). Reading the
  // real key would mean executing the channel factory (getMe, state-dir creation) — wrong at plan time
  // — so the runbook states the assumption instead of silently printing a stale path for remapped glue.
  const post: string[] = [];
  if (channels.includes("telegram")) {
    post.push(
      `# After deploy — register the Telegram webhook. The path assumes the default route (POST /telegram);`,
      `# if you remapped it in channels/telegram.ts, use your path. secret_token MUST equal TELEGRAM_SECRET_TOKEN:`,
      `curl "https://api.telegram.org/bot<TELEGRAM_BOT_TOKEN>/setWebhook" \\`,
      `  -d url=https://${appName}.fly.dev/telegram -d secret_token=<TELEGRAM_SECRET_TOKEN>`,
    );
  }
  if (channels.includes("github")) {
    post.push(
      `# After deploy — set the GitHub webhook (repo Settings → Webhooks). Path assumes the default route`,
      `# (POST /webhook); if you remapped it in channels/github.ts, use your path:`,
      `#   Payload URL = https://${appName}.fly.dev/webhook, content type application/json, secret = GITHUB_WEBHOOK_SECRET`,
    );
  }
  if (post.length > 0) runbook.push(``, ...post);

  // Single-machine tier: state lives on ONE volume tied to ONE machine. Scaling to multiple machines
  // splits state (each gets its own volume) — that needs a shared/external backend, not this recipe.
  runbook.push(
    ``,
    `# Keep this a SINGLE machine: the /data volume (and all state on it) is tied to one machine.`,
    `# Multiple machines would each get their own volume and split sessions/turns — don't scale past 1.`,
  );

  return { artifacts, runbook };
}

/**
 * The `app` name from an existing fly.toml's `app = "…"` line, or undefined if absent — the KEEP-mode
 * single source (a user who renamed the app is not overridden by the basename guess). Accepts TOML's
 * double OR single quotes; anything else (or no `app`) is undefined → the caller falls back to basename.
 */
export function parseFlyAppName(toml: string): string | undefined {
  return toml.match(/^\s*app\s*=\s*["']([^"']+)["']/m)?.[1];
}

/** Sanitize a directory basename into a Fly app name: lowercase, [a-z0-9-], must start with a letter. */
export function toFlyAppName(basename: string): string {
  const slug = basename
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return /^[a-z]/.test(slug) ? slug : `app-${slug || "agent"}`;
}
